import ABD.BQD.Bit.Mirror
import ABD.BQD.Bit.Addition
import ABD.BQD.Bit.CarryShift

namespace ABD
namespace BQD
namespace Bit

/-- A common-width bit system for three natural numbers.

This is still independent of ABC.  Later layers may add hypotheses such as
`a + b = c`, coprimality, or ABC-specific restrictions. -/
structure System where
  w : ℕ
  a : ℕ
  b : ℕ
  c : ℕ

namespace System

/-- The additive BQD comparing `a` and `b` at the common width. -/
def additive (S : System) : Decomp ℕ :=
  decomp S.w S.a S.b

/-- The mirror-pair BQD for `a`. -/
def mirrorA (S : System) : Decomp ℕ :=
  mirrorPair S.w S.a

/-- The mirror-pair BQD for `b`. -/
def mirrorB (S : System) : Decomp ℕ :=
  mirrorPair S.w S.b

/-- The mirror-pair BQD for `c`. -/
def mirrorC (S : System) : Decomp ℕ :=
  mirrorPair S.w S.c

/-- Raw carry generated by the additive BQD and incoming carry mask. -/
def rawCarry (S : System) (incoming : Finset ℕ) : Finset ℕ :=
  S.additive.carryStep incoming

/-- Bounded next carry inside the common width. -/
def nextCarry (S : System) (incoming : Finset ℕ) : Finset ℕ :=
  boundedCarryStep S.w S.additive incoming

/-- Overflow predicate at one carry step of the additive BQD. -/
def overflowAt (S : System) (incoming : Finset ℕ) : Prop :=
  overflowAtStep S.w S.additive incoming

/-- No-overflow predicate at one carry step of the additive BQD. -/
def noOverflowAt (S : System) (incoming : Finset ℕ) : Prop :=
  noOverflowAtStep S.w S.additive incoming

@[simp] theorem additive_U (S : System) :
    S.additive.U = bitUniverse S.w := rfl

@[simp] theorem additive_L (S : System) :
    S.additive.L = bitActive S.w S.a := rfl

@[simp] theorem additive_R (S : System) :
    S.additive.R = bitActive S.w S.b := rfl

@[simp] theorem mirrorA_U (S : System) :
    S.mirrorA.U = bitUniverse S.w := rfl

@[simp] theorem mirrorB_U (S : System) :
    S.mirrorB.U = bitUniverse S.w := rfl

@[simp] theorem mirrorC_U (S : System) :
    S.mirrorC.U = bitUniverse S.w := rfl

@[simp] theorem rawCarry_eq (S : System) (incoming : Finset ℕ) :
    S.rawCarry incoming = S.additive.carryStep incoming := rfl

@[simp] theorem nextCarry_eq (S : System) (incoming : Finset ℕ) :
    S.nextCarry incoming = boundedCarryStep S.w S.additive incoming := rfl

/-- The next carry mask always remains inside the common-width bit universe. -/
theorem nextCarry_subset_bitUniverse (S : System) (incoming : Finset ℕ) :
    S.nextCarry incoming ⊆ bitUniverse S.w := by
  exact boundedCarryStep_subset_bitUniverse S.w S.additive incoming

/-- No overflow at a system carry step is equivalent to every raw carry position
being shiftable inside the common-width bit universe. -/
theorem noOverflowAt_iff_forall_shiftable (S : System) (incoming : Finset ℕ) :
    S.noOverflowAt incoming ↔
      ∀ i, i ∈ S.rawCarry incoming → i + 1 ∈ bitUniverse S.w := by
  exact noOverflowAtStep_iff_forall_shiftable S.w S.additive incoming

end System
end Bit
end BQD
end ABD
