/-
  ABD.ApparitionDepth.BranchSeedRootProof

  Step 16 of the Apparition-Depth Decomposition project.

  This file proves the first real root property of the branch seed:

      seed = g ^ (((p - 1) / d) * j)

  is a `d`-th root modulo `p`, assuming `g` is a primitive root modulo `p` in the
  wrapper sense introduced in `PrimitiveRootBridge`.

  This stays at level `p` only.  Lifting the root from modulo `p` to modulo
  `p^r` is the job of the later Hensel/Teichmuller layers.
-/

import ABD.ApparitionDepth.PrimitiveRootBridge

namespace ApparitionDepth

/-- The branch seed generated by `g` is a `d`-th root modulo `p`. -/
def BranchSeedRootModP (g p d j : Nat) : Prop :=
  (branchSeedValue g p d j) ^ d = 1

/-- Constructor for `BranchSeedRootModP`. -/
theorem branchSeedRootModP_intro {g p d j : Nat}
    (h : (branchSeedValue g p d j) ^ d = 1) :
    BranchSeedRootModP g p d j :=
  h

/-- Projection from `BranchSeedRootModP`. -/
theorem branchSeedRootModP_eq {g p d j : Nat}
    (h : BranchSeedRootModP g p d j) :
    (branchSeedValue g p d j) ^ d = 1 :=
  h

/-- If `g` is primitive modulo `p`, then the branch seed is a `d`-th root modulo
`p`. -/
theorem branchSeedValue_pow_eq_one_of_primitiveRoot
    {g p d j : Nat}
    (hprim : PrimitiveRootModP g p)
    (hparams : BranchParams p d j) :
    (branchSeedValue g p d j) ^ d = 1 := by
  have hdiv : p - 1 ∣ branchSeedExponent p d j * d :=
    p_sub_one_dvd_branchSeedExponent_mul_d_of_branchParams hparams
  have hpow : ((g : ZMod p) ^ (branchSeedExponent p d j * d) = 1) :=
    residuePowOne_of_primitiveRootModP_dvd hprim hdiv
  unfold branchSeedValue
  rw [←pow_mul]
  exact hpow

/-- Predicate form of the previous theorem. -/
theorem branchSeedRootModP_of_primitiveRoot
    {g p d j : Nat}
    (hprim : PrimitiveRootModP g p)
    (hparams : BranchParams p d j) :
    BranchSeedRootModP g p d j :=
  branchSeedRootModP_intro
    (branchSeedValue_pow_eq_one_of_primitiveRoot hprim hparams)

/-- If `omega` is represented by the branch seed, then `omega^d = 1` modulo `p`. -/
theorem branchSeedModP_pow_eq_one_of_primitiveRoot
    {g omega p d j : Nat}
    (hprim : PrimitiveRootModP g p)
    (hparams : BranchParams p d j)
    (hseed : BranchSeedModP g omega p d j) :
    ((omega : ZMod p) ^ d = 1) := by
  have hseed' : (omega : ZMod p) = branchSeedValue g p d j :=
    branchSeedModP_seedValue hseed
  rw [hseed']
  exact branchSeedValue_pow_eq_one_of_primitiveRoot hprim hparams

/-- The branch seed gives an omega root at the first finite level `p^1`. -/
theorem omegaRootAtLevel_one_of_branchSeed_of_primitiveRoot
    {g omega p d j : Nat}
    (hprim : PrimitiveRootModP g p)
    (hparams : BranchParams p d j)
    (hseed : BranchSeedModP g omega p d j) :
    OmegaRootAtLevel omega p d 1 := by
  unfold OmegaRootAtLevel ResidueDepthAtLeast
  rw [Nat.pow_one]
  exact branchSeedModP_pow_eq_one_of_primitiveRoot
    (g := g) (omega := omega) (p := p) (d := d) (j := j)
    hprim hparams hseed

/-- Seed plus primitive-root data gives a seeded root at level `p^1`. -/
theorem seededRootAtLevel_one_of_branchSeed_of_primitiveRoot
    {g omega p d j : Nat}
    (hprim : PrimitiveRootModP g p)
    (hparams : BranchParams p d j)
    (hseed : BranchSeedModP g omega p d j) :
    SeededRootAtLevel g omega p d j 1 :=
  seededRootAtLevel_intro hseed
    (omegaRootAtLevel_one_of_branchSeed_of_primitiveRoot hprim hparams hseed)

/-- Primitive-root seed data gives a branch representative at level `p^1`. -/
theorem omegaBranchAtLevel_one_of_branchSeed_of_primitiveRoot
    {g omega p d j : Nat}
    (hprim : PrimitiveRootModP g p)
    (hparams : BranchParams p d j)
    (hseed : BranchSeedModP g omega p d j) :
    OmegaBranchAtLevel g omega p d j 1 :=
  omegaBranchAtLevel_intro hparams hseed
    (omegaRootAtLevel_one_of_branchSeed_of_primitiveRoot hprim hparams hseed)

/-- Primitive-root seed data gives an existential omega representative at level
`p^1`. -/
theorem omegaRepresentative_one_of_branchSeed_of_primitiveRoot
    {g omega p d j : Nat}
    (hprim : PrimitiveRootModP g p)
    (hparams : BranchParams p d j)
    (hseed : BranchSeedModP g omega p d j) :
    OmegaRepresentative omega p d j 1 :=
  omegaRepresentative_intro hparams hseed
    (omegaRootAtLevel_one_of_branchSeed_of_primitiveRoot hprim hparams hseed)

/-- Direct constructor for branch membership at level `p^1`. -/
theorem baseInOmegaBranch_one_of_branchSeed_of_primitiveRoot
    {ell g omega p d j : Nat}
    (hcongr : (ell : ZMod (p ^ 1)) = (omega : ZMod (p ^ 1)))
    (hprim : PrimitiveRootModP g p)
    (hparams : BranchParams p d j)
    (hseed : BranchSeedModP g omega p d j) :
    BaseInOmegaBranch ell omega p d j 1 :=
  baseInOmegaBranch_intro hcongr
    (omegaRepresentative_one_of_branchSeed_of_primitiveRoot hprim hparams hseed)

/-- Consequently, a positive base in this level-one branch has Core depth at
least `1`. -/
theorem depthAtLeast_one_of_branchSeed_of_primitiveRoot
    {ell g omega p d j : Nat}
    (hcongr : (ell : ZMod (p ^ 1)) = (omega : ZMod (p ^ 1)))
    (hprim : PrimitiveRootModP g p)
    (hparams : BranchParams p d j)
    (hseed : BranchSeedModP g omega p d j)
    (hell_pos : 0 < ell) :
    DepthAtLeast ell p d 1 :=
  depthAtLeast_of_baseInOmegaBranch_of_base_pos
    (baseInOmegaBranch_one_of_branchSeed_of_primitiveRoot
      hcongr hprim hparams hseed)
    hell_pos

end ApparitionDepth
