/-
  ABD.ApparitionDepth.HenselDerivativeCondition

  Step 20A of the Apparition-Depth Decomposition project.

  This file isolates the derivative condition needed for the later Hensel
  existence/uniqueness proofs.

  For the polynomial

      f(X) = X^d - 1,

  the formal derivative is

      f'(X) = d * X^(d - 1).

  Hensel lifting requires the seed to be a simple root modulo `p`, i.e. the root
  condition modulo `p` together with the nonvanishing derivative condition modulo
  `p`.

  This file does not yet prove the analytic/algebraic Hensel lemma.  It only
  names the derivative condition and proves the transport facts connecting it to
  the branch-seed and Hensel-lift interfaces already built.
-/

import ABD.ApparitionDepth.HenselLiftUniqueness

namespace ApparitionDepth

/-! ## Derivative value for `X^d - 1` -/

/-- The derivative value of `X^d - 1` at a natural representative `x`, read in
`ZMod p`:

`d * x^(d - 1)`. -/
def branchDerivativeValue (x p d : Nat) : ZMod p :=
  (d : ZMod p) * (x : ZMod p) ^ (d - 1)

/-- The derivative value at the branch seed generated by `g`. -/
def branchSeedDerivativeValue (g p d j : Nat) : ZMod p :=
  (d : ZMod p) * (branchSeedValue g p d j) ^ (d - 1)

/-- Unfolding helper for the derivative value. -/
theorem branchDerivativeValue_def (x p d : Nat) :
    branchDerivativeValue x p d =
      (d : ZMod p) * (x : ZMod p) ^ (d - 1) :=
  rfl

/-- Unfolding helper for the branch-seed derivative value. -/
theorem branchSeedDerivativeValue_def (g p d j : Nat) :
    branchSeedDerivativeValue g p d j =
      (d : ZMod p) * (branchSeedValue g p d j) ^ (d - 1) :=
  rfl

/-! ## Nonvanishing derivative conditions -/

/-- The derivative of `X^d - 1` at `omega` is nonzero modulo `p`. -/
def HenselDerivativeNonzeroModP (omega p d : Nat) : Prop :=
  branchDerivativeValue omega p d ≠ 0

/-- The derivative of `X^d - 1` at the generated branch seed is nonzero modulo
`p`. -/
def BranchSeedDerivativeNonzeroModP (g p d j : Nat) : Prop :=
  branchSeedDerivativeValue g p d j ≠ 0

/-- Constructor for the derivative nonzero condition. -/
theorem henselDerivativeNonzeroModP_intro {omega p d : Nat}
    (h : branchDerivativeValue omega p d ≠ 0) :
    HenselDerivativeNonzeroModP omega p d :=
  h

/-- Projection from the derivative nonzero condition. -/
theorem henselDerivativeNonzeroModP_ne {omega p d : Nat}
    (h : HenselDerivativeNonzeroModP omega p d) :
    branchDerivativeValue omega p d ≠ 0 :=
  h

/-- Constructor for the branch-seed derivative nonzero condition. -/
theorem branchSeedDerivativeNonzeroModP_intro {g p d j : Nat}
    (h : branchSeedDerivativeValue g p d j ≠ 0) :
    BranchSeedDerivativeNonzeroModP g p d j :=
  h

/-- Projection from the branch-seed derivative nonzero condition. -/
theorem branchSeedDerivativeNonzeroModP_ne {g p d j : Nat}
    (h : BranchSeedDerivativeNonzeroModP g p d j) :
    branchSeedDerivativeValue g p d j ≠ 0 :=
  h

/-- If `omega` is the branch seed modulo `p`, then derivative nonvanishing at the
seed transports to derivative nonvanishing at `omega`. -/
theorem henselDerivativeNonzero_of_branchSeedDerivativeNonzero
    {g omega p d j : Nat}
    (hseed : BranchSeedModP g omega p d j)
    (hderiv : BranchSeedDerivativeNonzeroModP g p d j) :
    HenselDerivativeNonzeroModP omega p d := by
  unfold HenselDerivativeNonzeroModP branchDerivativeValue
    BranchSeedDerivativeNonzeroModP branchSeedDerivativeValue at *
  have hseed' : (omega : ZMod p) = branchSeedValue g p d j :=
    branchSeedModP_seedValue hseed
  rw [hseed']
  exact hderiv

/-! ## Simple-root packages -/

/-- A root of `X^d - 1` modulo `p` together with the Hensel derivative condition.
This is the finite-level simple-root condition for a concrete representative. -/
def SimpleRootModP (omega p d : Nat) : Prop :=
  ((omega : ZMod p) ^ d = 1) ∧ HenselDerivativeNonzeroModP omega p d

/-- The branch seed is a simple root modulo `p`: it is a `d`-th root and its
Hensel derivative is nonzero. -/
def BranchSeedSimpleRootModP (g p d j : Nat) : Prop :=
  BranchSeedRootModP g p d j ∧ BranchSeedDerivativeNonzeroModP g p d j

/-- Constructor for `SimpleRootModP`. -/
theorem simpleRootModP_intro {omega p d : Nat}
    (hroot : ((omega : ZMod p) ^ d = 1))
    (hderiv : HenselDerivativeNonzeroModP omega p d) :
    SimpleRootModP omega p d :=
  ⟨hroot, hderiv⟩

/-- Projection: a simple root is a root. -/
theorem simpleRootModP_root {omega p d : Nat}
    (h : SimpleRootModP omega p d) :
    ((omega : ZMod p) ^ d = 1) :=
  h.1

/-- Projection: a simple root satisfies the derivative condition. -/
theorem simpleRootModP_derivative {omega p d : Nat}
    (h : SimpleRootModP omega p d) :
    HenselDerivativeNonzeroModP omega p d :=
  h.2

/-- Constructor for `BranchSeedSimpleRootModP`. -/
theorem branchSeedSimpleRootModP_intro {g p d j : Nat}
    (hroot : BranchSeedRootModP g p d j)
    (hderiv : BranchSeedDerivativeNonzeroModP g p d j) :
    BranchSeedSimpleRootModP g p d j :=
  ⟨hroot, hderiv⟩

/-- Projection: the branch seed is a root. -/
theorem branchSeedSimpleRootModP_root {g p d j : Nat}
    (h : BranchSeedSimpleRootModP g p d j) :
    BranchSeedRootModP g p d j :=
  h.1

/-- Projection: the branch seed has nonzero derivative. -/
theorem branchSeedSimpleRootModP_derivative {g p d j : Nat}
    (h : BranchSeedSimpleRootModP g p d j) :
    BranchSeedDerivativeNonzeroModP g p d j :=
  h.2

/-- Primitive-root data proves the root part of the simple-root condition; the
nonzero derivative part is supplied as the Step-20A condition. -/
theorem branchSeedSimpleRootModP_of_primitiveRoot_derivative
    {g p d j : Nat}
    (hprim : PrimitiveRootModP g p)
    (hparams : BranchParams p d j)
    (hderiv : BranchSeedDerivativeNonzeroModP g p d j) :
    BranchSeedSimpleRootModP g p d j :=
  branchSeedSimpleRootModP_intro
    (branchSeedRootModP_of_primitiveRoot hprim hparams)
    hderiv

/-- A simple branch seed transports to a simple concrete representative `omega`
whenever `omega` is the branch seed modulo `p`. -/
theorem simpleRootModP_of_branchSeedSimpleRoot
    {g omega p d j : Nat}
    (hseed : BranchSeedModP g omega p d j)
    (hsimple : BranchSeedSimpleRootModP g p d j) :
    SimpleRootModP omega p d := by
  refine ⟨?_, ?_⟩
  · have hseed' : (omega : ZMod p) = branchSeedValue g p d j :=
      branchSeedModP_seedValue hseed
    rw [hseed']
    exact branchSeedRootModP_eq (branchSeedSimpleRootModP_root hsimple)
  · exact henselDerivativeNonzero_of_branchSeedDerivativeNonzero hseed
      (branchSeedSimpleRootModP_derivative hsimple)

/-- Direct form: primitive-root data plus the derivative condition makes any
seed representative `omega` a simple root modulo `p`. -/
theorem simpleRootModP_of_branchSeed_of_primitiveRoot_derivative
    {g omega p d j : Nat}
    (hseed : BranchSeedModP g omega p d j)
    (hprim : PrimitiveRootModP g p)
    (hparams : BranchParams p d j)
    (hderiv : BranchSeedDerivativeNonzeroModP g p d j) :
    SimpleRootModP omega p d :=
  simpleRootModP_of_branchSeedSimpleRoot hseed
    (branchSeedSimpleRootModP_of_primitiveRoot_derivative hprim hparams hderiv)

/-! ## Compatibility with the Hensel-lift interface -/

/-- A level-one Hensel branch lift together with the derivative condition.  This
is the exact finite datum that later Hensel existence/uniqueness proofs need as
input. -/
def HenselAdmissibleLiftAtLevelOne (g omega p d j : Nat) : Prop :=
  HenselBranchLiftAtLevel g omega p d j 1 ∧ HenselDerivativeNonzeroModP omega p d

/-- Constructor for the level-one admissible lift package. -/
theorem henselAdmissibleLiftAtLevelOne_intro {g omega p d j : Nat}
    (hlift : HenselBranchLiftAtLevel g omega p d j 1)
    (hderiv : HenselDerivativeNonzeroModP omega p d) :
    HenselAdmissibleLiftAtLevelOne g omega p d j :=
  ⟨hlift, hderiv⟩

/-- Projection: an admissible level-one lift is a level-one lift. -/
theorem henselAdmissibleLiftAtLevelOne_lift {g omega p d j : Nat}
    (h : HenselAdmissibleLiftAtLevelOne g omega p d j) :
    HenselBranchLiftAtLevel g omega p d j 1 :=
  h.1

/-- Projection: an admissible level-one lift has nonzero derivative. -/
theorem henselAdmissibleLiftAtLevelOne_derivative {g omega p d j : Nat}
    (h : HenselAdmissibleLiftAtLevelOne g omega p d j) :
    HenselDerivativeNonzeroModP omega p d :=
  h.2

/-- Primitive-root seed data plus the derivative condition gives the admissible
level-one input for later Hensel lifting. -/
theorem henselAdmissibleLiftAtLevelOne_of_branchSeed_of_primitiveRoot_derivative
    {g omega p d j : Nat}
    (hprim : PrimitiveRootModP g p)
    (hparams : BranchParams p d j)
    (hseed : BranchSeedModP g omega p d j)
    (hderiv : BranchSeedDerivativeNonzeroModP g p d j) :
    HenselAdmissibleLiftAtLevelOne g omega p d j := by
  refine ⟨?_, ?_⟩
  · exact henselBranchLiftAtLevel_intro_of_seed hparams hseed
      (omegaRootAtLevel_one_of_branchSeed_of_primitiveRoot hprim hparams hseed)
  · exact henselDerivativeNonzero_of_branchSeedDerivativeNonzero hseed hderiv

end ApparitionDepth
