/-
  ABD.ApparitionDepth.HenselLiftInterface

  Step 17 of the Apparition-Depth Decomposition project.

  This file introduces a lightweight interface for Hensel lifts of the finite
  branch seed.

  It does not prove the Hensel existence theorem.  Instead, it names the data
  that a later Hensel/Teichmuller construction must provide:

    * an `omega` congruent to the branch seed modulo `p`;
    * the lifted root condition `omega^d = 1` modulo `p^r`.

  Once such data is available, this interface repackages it as the existing
  `OmegaBranchAtLevel`, `OmegaRepresentative`, and `BaseInOmegaBranch` objects.
-/

import ABD.ApparitionDepth.BranchSeedRootProof

namespace ApparitionDepth

/-! ## Seed congruence and Hensel-lift data -/

/-- `omega` extends the seed representative modulo `p`. -/
def SeedCongruentModP (seed omega p : Nat) : Prop :=
  (omega : ZMod p) = (seed : ZMod p)

/-- A Hensel lift of a concrete seed: congruent to the seed modulo `p`, and a
`d`-th root at precision `p^r`. -/
def HenselLiftOfSeed (seed omega p d r : Nat) : Prop :=
  SeedCongruentModP seed omega p ∧ OmegaRootAtLevel omega p d r

/-- A Hensel lift of the branch seed generated by `g`.

This is the finite-level form of:

`omega ≡ g^(((p - 1) / d) * j) mod p`, and `omega^d = 1 mod p^r`. -/
def HenselLiftOfBranchSeed (g omega p d j r : Nat) : Prop :=
  (omega : ZMod p) = branchSeedValue g p d j ∧ OmegaRootAtLevel omega p d r

/-- A branch Hensel lift at level `p^r`: branch parameters plus lifted seed data. -/
def HenselBranchLiftAtLevel (g omega p d j r : Nat) : Prop :=
  BranchParams p d j ∧ HenselLiftOfBranchSeed g omega p d j r

/-! ## Basic projections and constructors -/

theorem seedCongruentModP_intro {seed omega p : Nat}
    (h : (omega : ZMod p) = (seed : ZMod p)) :
    SeedCongruentModP seed omega p :=
  h

theorem seedCongruentModP_eq {seed omega p : Nat}
    (h : SeedCongruentModP seed omega p) :
    (omega : ZMod p) = (seed : ZMod p) :=
  h

theorem henselLiftOfSeed_seed {seed omega p d r : Nat}
    (h : HenselLiftOfSeed seed omega p d r) :
    SeedCongruentModP seed omega p :=
  h.1

theorem henselLiftOfSeed_root {seed omega p d r : Nat}
    (h : HenselLiftOfSeed seed omega p d r) :
    OmegaRootAtLevel omega p d r :=
  h.2

theorem henselLiftOfBranchSeed_seedValue {g omega p d j r : Nat}
    (h : HenselLiftOfBranchSeed g omega p d j r) :
    (omega : ZMod p) = branchSeedValue g p d j :=
  h.1

theorem henselLiftOfBranchSeed_seed {g omega p d j r : Nat}
    (h : HenselLiftOfBranchSeed g omega p d j r) :
    BranchSeedModP g omega p d j :=
  branchSeedModP_intro h.1

theorem henselLiftOfBranchSeed_root {g omega p d j r : Nat}
    (h : HenselLiftOfBranchSeed g omega p d j r) :
    OmegaRootAtLevel omega p d r :=
  h.2

theorem henselBranchLiftAtLevel_params {g omega p d j r : Nat}
    (h : HenselBranchLiftAtLevel g omega p d j r) :
    BranchParams p d j :=
  h.1

theorem henselBranchLiftAtLevel_lift {g omega p d j r : Nat}
    (h : HenselBranchLiftAtLevel g omega p d j r) :
    HenselLiftOfBranchSeed g omega p d j r :=
  h.2

theorem henselBranchLiftAtLevel_seed {g omega p d j r : Nat}
    (h : HenselBranchLiftAtLevel g omega p d j r) :
    BranchSeedModP g omega p d j :=
  henselLiftOfBranchSeed_seed h.2

theorem henselBranchLiftAtLevel_root {g omega p d j r : Nat}
    (h : HenselBranchLiftAtLevel g omega p d j r) :
    OmegaRootAtLevel omega p d r :=
  henselLiftOfBranchSeed_root h.2

/-- Constructor from a seed equality and a root condition. -/
theorem henselBranchLiftAtLevel_intro {g omega p d j r : Nat}
    (hparams : BranchParams p d j)
    (hseed : (omega : ZMod p) = branchSeedValue g p d j)
    (hroot : OmegaRootAtLevel omega p d r) :
    HenselBranchLiftAtLevel g omega p d j r :=
  ⟨hparams, hseed, hroot⟩

/-- Constructor from the existing `BranchSeedModP` predicate. -/
theorem henselBranchLiftAtLevel_intro_of_seed {g omega p d j r : Nat}
    (hparams : BranchParams p d j)
    (hseed : BranchSeedModP g omega p d j)
    (hroot : OmegaRootAtLevel omega p d r) :
    HenselBranchLiftAtLevel g omega p d j r :=
  henselBranchLiftAtLevel_intro hparams (branchSeedModP_seedValue hseed) hroot

/-! ## Agreement with the existing omega-branch language -/

/-- Hensel branch lift data is exactly the same interface as `OmegaBranchAtLevel`,
with the seed written using `branchSeedValue`. -/
theorem henselBranchLiftAtLevel_iff_omegaBranchAtLevel {g omega p d j r : Nat} :
    HenselBranchLiftAtLevel g omega p d j r ↔
      OmegaBranchAtLevel g omega p d j r := by
  constructor
  · intro h
    exact omegaBranchAtLevel_intro
      (henselBranchLiftAtLevel_params h)
      (henselBranchLiftAtLevel_seed h)
      (henselBranchLiftAtLevel_root h)
  · intro h
    exact henselBranchLiftAtLevel_intro_of_seed
      (omegaBranchAtLevel_params h)
      (omegaBranchAtLevel_seed h)
      (omegaBranchAtLevel_root h)

/-- Convert Hensel branch lift data to `OmegaBranchAtLevel`. -/
theorem omegaBranchAtLevel_of_henselBranchLiftAtLevel {g omega p d j r : Nat}
    (h : HenselBranchLiftAtLevel g omega p d j r) :
    OmegaBranchAtLevel g omega p d j r :=
  (henselBranchLiftAtLevel_iff_omegaBranchAtLevel
    (g := g) (omega := omega) (p := p) (d := d) (j := j) (r := r)).mp h

/-- Convert `OmegaBranchAtLevel` to Hensel branch lift data. -/
theorem henselBranchLiftAtLevel_of_omegaBranchAtLevel {g omega p d j r : Nat}
    (h : OmegaBranchAtLevel g omega p d j r) :
    HenselBranchLiftAtLevel g omega p d j r :=
  (henselBranchLiftAtLevel_iff_omegaBranchAtLevel
    (g := g) (omega := omega) (p := p) (d := d) (j := j) (r := r)).mpr h

/-- Hensel branch lift data gives an existential omega representative. -/
theorem omegaRepresentative_of_henselBranchLiftAtLevel {g omega p d j r : Nat}
    (h : HenselBranchLiftAtLevel g omega p d j r) :
    OmegaRepresentative omega p d j r :=
  omegaRepresentative_intro
    (henselBranchLiftAtLevel_params h)
    (henselBranchLiftAtLevel_seed h)
    (henselBranchLiftAtLevel_root h)

/-- A base congruent to a Hensel lift lies in the corresponding omega branch. -/
theorem baseInOmegaBranch_of_henselBranchLiftAtLevel
    {ell g omega p d j r : Nat}
    (hcongr : (ell : ZMod (p ^ r)) = (omega : ZMod (p ^ r)))
    (hlift : HenselBranchLiftAtLevel g omega p d j r) :
    BaseInOmegaBranch ell omega p d j r :=
  baseInOmegaBranch_intro hcongr
    (omegaRepresentative_of_henselBranchLiftAtLevel hlift)

/-- Consequently, a positive base congruent to a Hensel lift has Core depth at
least `r`. -/
theorem depthAtLeast_of_henselBranchLiftAtLevel_of_base_pos
    {ell g omega p d j r : Nat}
    (hcongr : (ell : ZMod (p ^ r)) = (omega : ZMod (p ^ r)))
    (hlift : HenselBranchLiftAtLevel g omega p d j r)
    (hell_pos : 0 < ell) :
    DepthAtLeast ell p d r :=
  depthAtLeast_of_baseInOmegaBranch_of_base_pos
    (baseInOmegaBranch_of_henselBranchLiftAtLevel hcongr hlift)
    hell_pos

end ApparitionDepth
