/-
  ABD.ApparitionDepth.HenselLiftExistence

  Step 18 of the Apparition-Depth Decomposition project.

  This file packages existence of Hensel lifts at a requested finite level.

  Important design choice:
    this is not yet the heavy Hensel theorem from analysis/algebra.  Instead, it
    gives a clean existence predicate and proves all transport consequences once
    an explicit lifted `omega` is provided.  A later file can prove this
    existence predicate from an actual Hensel lemma.
-/

import ABD.ApparitionDepth.HenselLiftInterface

namespace ApparitionDepth

/-! ## Existence predicates -/

/-- There exists a Hensel lift of the branch seed generated by `g` at level
`p^r`. -/
def HenselLiftExists (g p d j r : Nat) : Prop :=
  ∃ omega : Nat, HenselBranchLiftAtLevel g omega p d j r

/-- There are compatible Hensel lifts at all positive finite levels. -/
def HenselLiftExistsForAllLevels (g p d j : Nat) : Prop :=
  ∀ r : Nat, 0 < r → HenselLiftExists g p d j r

/-- A base `ell` is congruent modulo `p^r` to some Hensel lift of the branch
seed. -/
def BaseHasHenselLift (ell g p d j r : Nat) : Prop :=
  ∃ omega : Nat,
    (ell : ZMod (p ^ r)) = (omega : ZMod (p ^ r)) ∧
      HenselBranchLiftAtLevel g omega p d j r

/-! ## Basic constructors and projections -/

theorem henselLiftExists_intro {g omega p d j r : Nat}
    (hlift : HenselBranchLiftAtLevel g omega p d j r) :
    HenselLiftExists g p d j r :=
  ⟨omega, hlift⟩

theorem henselLiftExists_witness {g p d j r : Nat}
    (h : HenselLiftExists g p d j r) :
    ∃ omega : Nat, HenselBranchLiftAtLevel g omega p d j r :=
  h

theorem henselLiftExistsForAllLevels_at {g p d j r : Nat}
    (h : HenselLiftExistsForAllLevels g p d j)
    (hr_pos : 0 < r) :
    HenselLiftExists g p d j r :=
  h r hr_pos

theorem baseHasHenselLift_intro {ell g omega p d j r : Nat}
    (hcongr : (ell : ZMod (p ^ r)) = (omega : ZMod (p ^ r)))
    (hlift : HenselBranchLiftAtLevel g omega p d j r) :
    BaseHasHenselLift ell g p d j r :=
  ⟨omega, hcongr, hlift⟩

theorem baseHasHenselLift_witness {ell g p d j r : Nat}
    (h : BaseHasHenselLift ell g p d j r) :
    ∃ omega : Nat,
      (ell : ZMod (p ^ r)) = (omega : ZMod (p ^ r)) ∧
        HenselBranchLiftAtLevel g omega p d j r :=
  h

/-! ## Producing existence from explicit root data -/

/-- Explicit seed and root data produce a Hensel-lift existence certificate. -/
theorem henselLiftExists_of_seed_root {g omega p d j r : Nat}
    (hparams : BranchParams p d j)
    (hseed : BranchSeedModP g omega p d j)
    (hroot : OmegaRootAtLevel omega p d r) :
    HenselLiftExists g p d j r :=
  henselLiftExists_intro
    (henselBranchLiftAtLevel_intro_of_seed hparams hseed hroot)

/-- Any existing `OmegaBranchAtLevel` certificate gives Hensel-lift existence. -/
theorem henselLiftExists_of_omegaBranchAtLevel {g omega p d j r : Nat}
    (hbranch : OmegaBranchAtLevel g omega p d j r) :
    HenselLiftExists g p d j r :=
  henselLiftExists_intro
    (henselBranchLiftAtLevel_of_omegaBranchAtLevel hbranch)

/-- The level-one primitive-root construction from Step 16 gives Hensel-lift
existence at level `1`. -/
theorem henselLiftExists_one_of_branchSeed_of_primitiveRoot {g omega p d j : Nat}
    (hprim : PrimitiveRootModP g p)
    (hparams : BranchParams p d j)
    (hseed : BranchSeedModP g omega p d j) :
    HenselLiftExists g p d j 1 :=
  henselLiftExists_of_seed_root hparams hseed
    (omegaRootAtLevel_one_of_branchSeed_of_primitiveRoot hprim hparams hseed)

/-! ## Transport consequences of existence -/

/-- Hensel-lift existence gives existence of an omega representative. -/
theorem omegaRepresentative_exists_of_henselLiftExists {g p d j r : Nat}
    (h : HenselLiftExists g p d j r) :
    ∃ omega : Nat, OmegaRepresentative omega p d j r := by
  rcases h with ⟨omega, hlift⟩
  exact ⟨omega, omegaRepresentative_of_henselBranchLiftAtLevel hlift⟩

/-- If a base is congruent to a Hensel lift, then it lies in an omega branch. -/
theorem baseInOmegaBranch_exists_of_baseHasHenselLift {ell g p d j r : Nat}
    (h : BaseHasHenselLift ell g p d j r) :
    ∃ omega : Nat, BaseInOmegaBranch ell omega p d j r := by
  rcases h with ⟨omega, hcongr, hlift⟩
  exact ⟨omega, baseInOmegaBranch_of_henselBranchLiftAtLevel hcongr hlift⟩

/-- If a positive base is congruent to a Hensel lift, then Core depth at least
`r` follows. -/
theorem depthAtLeast_of_baseHasHenselLift_of_base_pos {ell g p d j r : Nat}
    (h : BaseHasHenselLift ell g p d j r)
    (hell_pos : 0 < ell) :
    DepthAtLeast ell p d r := by
  rcases h with ⟨omega, hcongr, hlift⟩
  exact depthAtLeast_of_henselBranchLiftAtLevel_of_base_pos hcongr hlift hell_pos

/-- With the standard valuation assumptions, a positive base congruent to a
Hensel lift has `r <= depthValue ell p d`. -/
theorem le_depthValue_of_baseHasHenselLift
    {ell g p d j r : Nat}
    [Fact (Nat.Prime p)]
    (hN : N ell d ≠ 0)
    (h : BaseHasHenselLift ell g p d j r)
    (hell_pos : 0 < ell) :
    r ≤ depthValue ell p d :=
  le_depthValue_of_depthAtLeast hN
    (depthAtLeast_of_baseHasHenselLift_of_base_pos h hell_pos)

end ApparitionDepth
