/-
  ABD.ApparitionDepth.TeichmullerFinite

  Step 20D of the Apparition-Depth Decomposition project.

  This file closes the finite Teichmuller/Hensel generation side at the level of
  the interfaces built in Steps 17--20C.

  Important precision about the status of the mathematics:

    * the heavy Hensel lemma itself is still represented by the theorem-shapes
      introduced in `HenselExistenceProofInterface`;
    * once those theorem-shapes are available, this file packages the resulting
      finite-level lift as the canonical finite Teichmuller representative;
    * it then sends that representative back into the omega-branch, Core depth,
      and valuation-depth pipelines already proved earlier.

  Thus the generation side is closed in the following sense:

      simple root input
      + Hensel exists-unique theorem-shape
      -> canonical finite Teichmuller representative omega[p,d,j,r]
      -> BaseInOmegaBranch
      -> DepthAtLeast
      -> r <= depthValue.
-/

import ABD.ApparitionDepth.HenselExistenceProofInterface

namespace ApparitionDepth

/-! ## Finite Teichmuller representatives -/

/-- A finite Teichmuller representative at level `p^r`.

At this finite/interface level, this is exactly a canonical Hensel lift of the
branch seed generated by `g`.  Later p-adic files can connect this finite object
to an actual p-adic Teichmuller representative. -/
def TeichmullerFiniteAtLevel (omega g p d j r : Nat) : Prop :=
  HenselLiftCanonicalRep omega g p d j r

/-- Existence of a finite Teichmuller representative at a fixed level. -/
def TeichmullerFiniteExistsAtLevel (g p d j r : Nat) : Prop :=
  ∃ omega : Nat, TeichmullerFiniteAtLevel omega g p d j r

/-- Existence of finite Teichmuller representatives at all positive levels. -/
def TeichmullerFiniteExistsForAllLevels (g p d j : Nat) : Prop :=
  ∀ r : Nat, 0 < r → TeichmullerFiniteExistsAtLevel g p d j r

/-- A base lies in the residue class of a finite Teichmuller representative. -/
def BaseInTeichmullerFiniteBranch (ell omega g p d j r : Nat) : Prop :=
  (ell : ZMod (p ^ r)) = (omega : ZMod (p ^ r)) ∧
    TeichmullerFiniteAtLevel omega g p d j r

/-- A base lies in some finite Teichmuller branch at the given level. -/
def BaseInSomeTeichmullerFiniteBranch (ell g p d j r : Nat) : Prop :=
  ∃ omega : Nat, BaseInTeichmullerFiniteBranch ell omega g p d j r

/-! ## Basic constructors and projections -/

/-- Constructor for finite Teichmuller representatives from a canonical Hensel
representative. -/
theorem teichmullerFiniteAtLevel_intro {omega g p d j r : Nat}
    (hcanon : HenselLiftCanonicalRep omega g p d j r) :
    TeichmullerFiniteAtLevel omega g p d j r :=
  hcanon

/-- A finite Teichmuller representative is a Hensel lift. -/
theorem teichmullerFiniteAtLevel_lift {omega g p d j r : Nat}
    (h : TeichmullerFiniteAtLevel omega g p d j r) :
    HenselBranchLiftAtLevel g omega p d j r :=
  henselLiftCanonicalRep_lift h

/-- A finite Teichmuller representative carries uniqueness. -/
theorem teichmullerFiniteAtLevel_unique {omega g p d j r : Nat}
    (h : TeichmullerFiniteAtLevel omega g p d j r) :
    HenselLiftUniqueAtLevel g p d j r :=
  henselLiftCanonicalRep_unique h

/-- Branch parameters carried by a finite Teichmuller representative. -/
theorem teichmullerFiniteAtLevel_params {omega g p d j r : Nat}
    (h : TeichmullerFiniteAtLevel omega g p d j r) :
    BranchParams p d j :=
  henselBranchLiftAtLevel_params (teichmullerFiniteAtLevel_lift h)

/-- Seed equality carried by a finite Teichmuller representative. -/
theorem teichmullerFiniteAtLevel_seed {omega g p d j r : Nat}
    (h : TeichmullerFiniteAtLevel omega g p d j r) :
    BranchSeedModP g omega p d j :=
  henselBranchLiftAtLevel_seed (teichmullerFiniteAtLevel_lift h)

/-- Root condition carried by a finite Teichmuller representative. -/
theorem teichmullerFiniteAtLevel_root {omega g p d j r : Nat}
    (h : TeichmullerFiniteAtLevel omega g p d j r) :
    OmegaRootAtLevel omega p d r :=
  henselBranchLiftAtLevel_root (teichmullerFiniteAtLevel_lift h)

/-- A finite Teichmuller representative gives an omega representative. -/
theorem omegaRepresentative_of_teichmullerFiniteAtLevel {omega g p d j r : Nat}
    (h : TeichmullerFiniteAtLevel omega g p d j r) :
    OmegaRepresentative omega p d j r :=
  omegaRepresentative_of_henselBranchLiftAtLevel (teichmullerFiniteAtLevel_lift h)

/-- Constructor for base membership in a finite Teichmuller branch. -/
theorem baseInTeichmullerFiniteBranch_intro {ell omega g p d j r : Nat}
    (hcongr : (ell : ZMod (p ^ r)) = (omega : ZMod (p ^ r)))
    (hteich : TeichmullerFiniteAtLevel omega g p d j r) :
    BaseInTeichmullerFiniteBranch ell omega g p d j r :=
  ⟨hcongr, hteich⟩

/-- Projection: congruence of the base to the finite Teichmuller representative. -/
theorem baseInTeichmullerFiniteBranch_congr {ell omega g p d j r : Nat}
    (h : BaseInTeichmullerFiniteBranch ell omega g p d j r) :
    (ell : ZMod (p ^ r)) = (omega : ZMod (p ^ r)) :=
  h.1

/-- Projection: the finite Teichmuller representative in a base membership. -/
theorem baseInTeichmullerFiniteBranch_teich {ell omega g p d j r : Nat}
    (h : BaseInTeichmullerFiniteBranch ell omega g p d j r) :
    TeichmullerFiniteAtLevel omega g p d j r :=
  h.2

/-- Constructor for existence of finite Teichmuller representative at a level. -/
theorem teichmullerFiniteExistsAtLevel_intro {omega g p d j r : Nat}
    (h : TeichmullerFiniteAtLevel omega g p d j r) :
    TeichmullerFiniteExistsAtLevel g p d j r :=
  ⟨omega, h⟩

/-- Constructor for existence of a base branch through a finite Teichmuller
representative. -/
theorem baseInSomeTeichmullerFiniteBranch_intro {ell omega g p d j r : Nat}
    (h : BaseInTeichmullerFiniteBranch ell omega g p d j r) :
    BaseInSomeTeichmullerFiniteBranch ell g p d j r :=
  ⟨omega, h⟩

/-! ## Agreement with omega branches and Hensel interfaces -/

/-- A finite Teichmuller representative is an omega branch representative. -/
theorem baseInOmegaBranch_of_baseInTeichmullerFiniteBranch
    {ell omega g p d j r : Nat}
    (h : BaseInTeichmullerFiniteBranch ell omega g p d j r) :
    BaseInOmegaBranch ell omega p d j r :=
  baseInOmegaBranch_of_henselBranchLiftAtLevel
    (baseInTeichmullerFiniteBranch_congr h)
    (teichmullerFiniteAtLevel_lift (baseInTeichmullerFiniteBranch_teich h))

/-- A base in some finite Teichmuller branch lies in some omega branch. -/
theorem exists_baseInOmegaBranch_of_baseInSomeTeichmullerFiniteBranch
    {ell g p d j r : Nat}
    (h : BaseInSomeTeichmullerFiniteBranch ell g p d j r) :
    ∃ omega : Nat, BaseInOmegaBranch ell omega p d j r := by
  rcases h with ⟨omega, hbranch⟩
  exact ⟨omega, baseInOmegaBranch_of_baseInTeichmullerFiniteBranch hbranch⟩

/-- Any two finite Teichmuller representatives of the same branch and level are
congruent modulo `p^r`. -/
theorem zmod_eq_of_two_teichmullerFiniteAtLevel
    {omega₁ omega₂ g p d j r : Nat}
    (h₁ : TeichmullerFiniteAtLevel omega₁ g p d j r)
    (h₂ : TeichmullerFiniteAtLevel omega₂ g p d j r) :
    (omega₁ : ZMod (p ^ r)) = (omega₂ : ZMod (p ^ r)) :=
  zmod_eq_of_two_henselBranchLiftAtLevel
    (teichmullerFiniteAtLevel_unique h₁)
    (teichmullerFiniteAtLevel_lift h₁)
    (teichmullerFiniteAtLevel_lift h₂)

/-- A base known to be congruent to some Hensel lift is congruent to a chosen
finite Teichmuller representative. -/
theorem baseHasHenselLift_congr_to_teichmullerFinite
    {ell omega g p d j r : Nat}
    (hbase : BaseHasHenselLift ell g p d j r)
    (hteich : TeichmullerFiniteAtLevel omega g p d j r) :
    (ell : ZMod (p ^ r)) = (omega : ZMod (p ^ r)) :=
  baseHasHenselLift_congr_to_canonical hbase hteich

/-- A base with some Hensel-lift witness lies in the finite Teichmuller branch of
any chosen finite Teichmuller representative. -/
theorem baseInTeichmullerFiniteBranch_of_baseHasHenselLift
    {ell omega g p d j r : Nat}
    (hbase : BaseHasHenselLift ell g p d j r)
    (hteich : TeichmullerFiniteAtLevel omega g p d j r) :
    BaseInTeichmullerFiniteBranch ell omega g p d j r :=
  ⟨baseHasHenselLift_congr_to_teichmullerFinite hbase hteich, hteich⟩

/-! ## Producing finite Teichmuller representatives -/

/-- Existing Hensel exists-unique data produces a finite Teichmuller representative. -/
theorem exists_teichmullerFiniteAtLevel_of_henselLiftExistsUnique
    {g p d j r : Nat}
    (h : HenselLiftExistsUnique g p d j r) :
    TeichmullerFiniteExistsAtLevel g p d j r := by
  rcases exists_henselLiftCanonicalRep_of_existsUnique h with ⟨omega, hcanon⟩
  exact ⟨omega, teichmullerFiniteAtLevel_intro hcanon⟩

/-- All-level Hensel exists-unique data produces finite Teichmuller
representatives at all positive levels. -/
theorem teichmullerFiniteExistsForAllLevels_of_henselLiftExistsUniqueForAllLevels
    {g p d j : Nat}
    (h : HenselLiftExistsUniqueForAllLevels g p d j) :
    TeichmullerFiniteExistsForAllLevels g p d j :=
  fun r hr_pos => exists_teichmullerFiniteAtLevel_of_henselLiftExistsUnique (h r hr_pos)

/-- Fixed-level simple-root exists-unique data produces a finite Teichmuller
representative, once a level-one admissible seed is provided. -/
theorem exists_teichmullerFiniteAtLevel_of_simpleRootExistsUniqueAtLevel
    {g omega0 p d j r : Nat}
    (h : HenselSimpleRootExistsUniqueAtLevel g p d j r)
    (hadm : HenselAdmissibleLiftAtLevelOne g omega0 p d j) :
    TeichmullerFiniteExistsAtLevel g p d j r := by
  rcases exists_henselLiftCanonicalRep_of_simpleRootExistsUniqueAtLevel h hadm with
    ⟨omega, hcanon⟩
  exact ⟨omega, teichmullerFiniteAtLevel_intro hcanon⟩

/-- Branch-seed primitive-root form: the simple-root exists-unique theorem-shape
produces a finite Teichmuller representative. -/
theorem exists_teichmullerFiniteAtLevel_of_branchSeed_primitiveRoot_derivative
    {g omega0 p d j r : Nat}
    (h : HenselSimpleRootExistsUniqueAtLevel g p d j r)
    (hprim : PrimitiveRootModP g p)
    (hparams : BranchParams p d j)
    (hseed : BranchSeedModP g omega0 p d j)
    (hderiv : BranchSeedDerivativeNonzeroModP g p d j) :
    TeichmullerFiniteExistsAtLevel g p d j r := by
  rcases exists_henselLiftCanonicalRep_of_branchSeed_primitiveRoot_derivative
      h hprim hparams hseed hderiv with ⟨omega, hcanon⟩
  exact ⟨omega, teichmullerFiniteAtLevel_intro hcanon⟩

/-- All-level branch-seed primitive-root form: the all-level simple-root
exists-unique theorem-shape produces finite Teichmuller representatives at every
positive level. -/
theorem teichmullerFiniteExistsForAllLevels_of_branchSeed_primitiveRoot_derivative
    {g omega0 p d j : Nat}
    (h : HenselSimpleRootExistsUniqueForAllLevels g p d j)
    (hprim : PrimitiveRootModP g p)
    (hparams : BranchParams p d j)
    (hseed : BranchSeedModP g omega0 p d j)
    (hderiv : BranchSeedDerivativeNonzeroModP g p d j) :
    TeichmullerFiniteExistsForAllLevels g p d j :=
  fun _r hr_pos =>
    exists_teichmullerFiniteAtLevel_of_branchSeed_primitiveRoot_derivative
      (henselSimpleRootExistsUniqueForAllLevels_at h hr_pos)
      hprim hparams hseed hderiv

/-! ## Producing base membership through finite Teichmuller representatives -/

/-- A base with a Hensel-lift witness and fixed-level exists-unique data lies in
some finite Teichmuller branch. -/
theorem exists_baseInTeichmullerFiniteBranch_of_baseHasHenselLift_of_existsUnique
    {ell g p d j r : Nat}
    (hbase : BaseHasHenselLift ell g p d j r)
    (huniq : HenselLiftExistsUnique g p d j r) :
    BaseInSomeTeichmullerFiniteBranch ell g p d j r := by
  rcases exists_teichmullerFiniteAtLevel_of_henselLiftExistsUnique huniq with
    ⟨omega, hteich⟩
  exact ⟨omega, baseInTeichmullerFiniteBranch_of_baseHasHenselLift hbase hteich⟩

/-- A base with a Hensel-lift witness and fixed-level simple-root exists-unique
data lies in some finite Teichmuller branch. -/
theorem exists_baseInTeichmullerFiniteBranch_of_baseHasHenselLift_of_simpleRootExistsUnique
    {ell g omega0 p d j r : Nat}
    (hbase : BaseHasHenselLift ell g p d j r)
    (h : HenselSimpleRootExistsUniqueAtLevel g p d j r)
    (hadm : HenselAdmissibleLiftAtLevelOne g omega0 p d j) :
    BaseInSomeTeichmullerFiniteBranch ell g p d j r :=
  exists_baseInTeichmullerFiniteBranch_of_baseHasHenselLift_of_existsUnique hbase
    (henselLiftExistsUnique_of_simpleRootExistsUniqueAtLevel h hadm)

/-- Branch-seed primitive-root form of the previous theorem. -/
theorem exists_baseInTeichmullerFiniteBranch_of_branchSeed_primitiveRoot_derivative
    {ell g omega0 p d j r : Nat}
    (hbase : BaseHasHenselLift ell g p d j r)
    (h : HenselSimpleRootExistsUniqueAtLevel g p d j r)
    (hprim : PrimitiveRootModP g p)
    (hparams : BranchParams p d j)
    (hseed : BranchSeedModP g omega0 p d j)
    (hderiv : BranchSeedDerivativeNonzeroModP g p d j) :
    BaseInSomeTeichmullerFiniteBranch ell g p d j r :=
  exists_baseInTeichmullerFiniteBranch_of_baseHasHenselLift_of_existsUnique hbase
    (henselLiftExistsUnique_of_branchSeed_of_primitiveRoot_derivative
      h hprim hparams hseed hderiv)

/-! ## Closing back to Core depth and valuation depth -/

/-- A positive base in a finite Teichmuller branch has Core depth at least `r`. -/
theorem depthAtLeast_of_baseInTeichmullerFiniteBranch_of_base_pos
    {ell omega g p d j r : Nat}
    (h : BaseInTeichmullerFiniteBranch ell omega g p d j r)
    (hell_pos : 0 < ell) :
    DepthAtLeast ell p d r :=
  depthAtLeast_of_baseInOmegaBranch_of_base_pos
    (baseInOmegaBranch_of_baseInTeichmullerFiniteBranch h)
    hell_pos

/-- A positive base in some finite Teichmuller branch has Core depth at least `r`. -/
theorem depthAtLeast_of_baseInSomeTeichmullerFiniteBranch_of_base_pos
    {ell g p d j r : Nat}
    (h : BaseInSomeTeichmullerFiniteBranch ell g p d j r)
    (hell_pos : 0 < ell) :
    DepthAtLeast ell p d r := by
  rcases h with ⟨omega, hbranch⟩
  exact depthAtLeast_of_baseInTeichmullerFiniteBranch_of_base_pos hbranch hell_pos

/-- With the standard valuation assumptions, a positive base in a finite
Teichmuller branch has `r <= depthValue ell p d`. -/
theorem le_depthValue_of_baseInTeichmullerFiniteBranch
    {ell omega g p d j r : Nat}
    [Fact (Nat.Prime p)]
    (hN : N ell d ≠ 0)
    (h : BaseInTeichmullerFiniteBranch ell omega g p d j r)
    (hell_pos : 0 < ell) :
    r ≤ depthValue ell p d :=
  le_depthValue_of_depthAtLeast hN
    (depthAtLeast_of_baseInTeichmullerFiniteBranch_of_base_pos h hell_pos)

/-- With the standard valuation assumptions, a positive base in some finite
Teichmuller branch has `r <= depthValue ell p d`. -/
theorem le_depthValue_of_baseInSomeTeichmullerFiniteBranch
    {ell g p d j r : Nat}
    [Fact (Nat.Prime p)]
    (hN : N ell d ≠ 0)
    (h : BaseInSomeTeichmullerFiniteBranch ell g p d j r)
    (hell_pos : 0 < ell) :
    r ≤ depthValue ell p d := by
  rcases h with ⟨omega, hbranch⟩
  exact le_depthValue_of_baseInTeichmullerFiniteBranch hN hbranch hell_pos

/-- Branch-seed primitive-root form: once a base has a Hensel-lift witness and
the fixed-level simple-root exists-unique theorem-shape is available, Core depth
at least `r` follows. -/
theorem depthAtLeast_of_branchSeed_primitiveRoot_derivative_baseHasHenselLift
    {ell g omega0 p d j r : Nat}
    (hbase : BaseHasHenselLift ell g p d j r)
    (h : HenselSimpleRootExistsUniqueAtLevel g p d j r)
    (hprim : PrimitiveRootModP g p)
    (hparams : BranchParams p d j)
    (hseed : BranchSeedModP g omega0 p d j)
    (hderiv : BranchSeedDerivativeNonzeroModP g p d j)
    (hell_pos : 0 < ell) :
    DepthAtLeast ell p d r :=
  depthAtLeast_of_baseInSomeTeichmullerFiniteBranch_of_base_pos
    (exists_baseInTeichmullerFiniteBranch_of_branchSeed_primitiveRoot_derivative
      hbase h hprim hparams hseed hderiv)
    hell_pos

/-- Branch-seed primitive-root form: with valuation assumptions, the same data
gives the depth lower bound `r <= depthValue ell p d`. -/
theorem le_depthValue_of_branchSeed_primitiveRoot_derivative_baseHasHenselLift
    {ell g omega0 p d j r : Nat}
    [Fact (Nat.Prime p)]
    (hN : N ell d ≠ 0)
    (hbase : BaseHasHenselLift ell g p d j r)
    (h : HenselSimpleRootExistsUniqueAtLevel g p d j r)
    (hprim : PrimitiveRootModP g p)
    (hparams : BranchParams p d j)
    (hseed : BranchSeedModP g omega0 p d j)
    (hderiv : BranchSeedDerivativeNonzeroModP g p d j)
    (hell_pos : 0 < ell) :
    r ≤ depthValue ell p d :=
  le_depthValue_of_baseInSomeTeichmullerFiniteBranch hN
    (exists_baseInTeichmullerFiniteBranch_of_branchSeed_primitiveRoot_derivative
      hbase h hprim hparams hseed hderiv)
    hell_pos

/-! ## Closing the apparition-depth package -/

/-- Combining the order side and the finite Teichmuller generation side: if `d` is
also the multiplicative-order first apparition index, then a base in the finite
Teichmuller branch gives a first apparition with depth at least `r`. -/
theorem firstWithDepthAtLeast_of_orderModIs_and_baseInTeichmullerFiniteBranch
    {ell omega g p d j r : Nat} {hcop : ell.Coprime p}
    (hord : OrderModIs ell p d hcop)
    (hd_pos : 0 < d)
    (hbranch : BaseInTeichmullerFiniteBranch ell omega g p d j r)
    (hell_pos : 0 < ell) :
    FirstAppearsWithDepthAtLeast ell p d r :=
  ⟨firstAppearsAt_of_orderModIs_pos_of_base_pos hord hd_pos hell_pos,
    depthAtLeast_of_baseInTeichmullerFiniteBranch_of_base_pos hbranch hell_pos⟩

/-- Existential version of the previous theorem. -/
theorem firstWithDepthAtLeast_of_orderModIs_and_baseInSomeTeichmullerFiniteBranch
    {ell g p d j r : Nat} {hcop : ell.Coprime p}
    (hord : OrderModIs ell p d hcop)
    (hd_pos : 0 < d)
    (hbranch : BaseInSomeTeichmullerFiniteBranch ell g p d j r)
    (hell_pos : 0 < ell) :
    FirstAppearsWithDepthAtLeast ell p d r :=
  ⟨firstAppearsAt_of_orderModIs_pos_of_base_pos hord hd_pos hell_pos,
    depthAtLeast_of_baseInSomeTeichmullerFiniteBranch_of_base_pos hbranch hell_pos⟩

/-- Fully packaged finite Teichmuller/Hensel generation theorem for AD depth.

This is the end of the finite generation pipeline built in Steps 13--20D:

* primitive-root branch seed data gives a level-one simple root once the
  derivative condition is supplied;
* the Hensel simple-root exists-unique theorem-shape produces a canonical finite
  Teichmuller representative;
* a base congruent to some lift is transported to that canonical representative;
* the base therefore has Core depth at least `r`.
-/
theorem finiteTeichmullerGeneration_depthAtLeast
    {ell g omega0 p d j r : Nat}
    (hbase : BaseHasHenselLift ell g p d j r)
    (h : HenselSimpleRootExistsUniqueAtLevel g p d j r)
    (hprim : PrimitiveRootModP g p)
    (hparams : BranchParams p d j)
    (hseed : BranchSeedModP g omega0 p d j)
    (hderiv : BranchSeedDerivativeNonzeroModP g p d j)
    (hell_pos : 0 < ell) :
    DepthAtLeast ell p d r :=
  depthAtLeast_of_branchSeed_primitiveRoot_derivative_baseHasHenselLift
    hbase h hprim hparams hseed hderiv hell_pos

/-- Fully packaged finite Teichmuller/Hensel generation theorem for valuation
lower bounds. -/
theorem finiteTeichmullerGeneration_le_depthValue
    {ell g omega0 p d j r : Nat}
    [Fact (Nat.Prime p)]
    (hN : N ell d ≠ 0)
    (hbase : BaseHasHenselLift ell g p d j r)
    (h : HenselSimpleRootExistsUniqueAtLevel g p d j r)
    (hprim : PrimitiveRootModP g p)
    (hparams : BranchParams p d j)
    (hseed : BranchSeedModP g omega0 p d j)
    (hderiv : BranchSeedDerivativeNonzeroModP g p d j)
    (hell_pos : 0 < ell) :
    r ≤ depthValue ell p d :=
  le_depthValue_of_branchSeed_primitiveRoot_derivative_baseHasHenselLift
    hN hbase h hprim hparams hseed hderiv hell_pos

/-- Fully packaged finite Teichmuller/Hensel generation theorem combined with the
order side of apparition. -/
theorem finiteTeichmullerGeneration_firstWithDepthAtLeast
    {ell g omega0 p d j r : Nat} {hcop : ell.Coprime p}
    (hord : OrderModIs ell p d hcop)
    (hd_pos : 0 < d)
    (hbase : BaseHasHenselLift ell g p d j r)
    (h : HenselSimpleRootExistsUniqueAtLevel g p d j r)
    (hprim : PrimitiveRootModP g p)
    (hparams : BranchParams p d j)
    (hseed : BranchSeedModP g omega0 p d j)
    (hderiv : BranchSeedDerivativeNonzeroModP g p d j)
    (hell_pos : 0 < ell) :
    FirstAppearsWithDepthAtLeast ell p d r :=
  ⟨firstAppearsAt_of_orderModIs_pos_of_base_pos hord hd_pos hell_pos,
    finiteTeichmullerGeneration_depthAtLeast
      hbase h hprim hparams hseed hderiv hell_pos⟩

end ApparitionDepth
