import ABD.Lattice.KernelSubmodule
import ABD.Lattice.SmallnessAbs
import ABD.Lattice.Nondegenerate

namespace ABD

/-- Two distinct coordinates in a finite support.

This is the Lean-friendly version of the condition that the support has at least
two usable prime directions.  A later file can connect this package to
`2 ≤ S.card`; the construction below only needs the actual two coordinates.
-/
structure SupportPair (S : Finset ℕ) where
  left : {p : ℕ // p ∈ S}
  right : {p : ℕ // p ∈ S}
  ne : left ≠ right

/-- The coordinate unit tangent vector at a support point. -/
def unitTangent (S : Finset ℕ) (i : {p : ℕ // p ∈ S}) : Tangent S :=
  fun j => if j = i then 1 else 0

@[simp] theorem unitTangent_self
    (S : Finset ℕ) (i : {p : ℕ // p ∈ S}) :
    unitTangent S i i = 1 := by
  simp [unitTangent]

@[simp] theorem unitTangent_of_ne
    (S : Finset ℕ) {i j : {p : ℕ // p ∈ S}} (h : j ≠ i) :
    unitTangent S i j = 0 := by
  simp [unitTangent, h]

/-- The raw coefficient of the additive constraint at a support coordinate. -/
def unitLinearCoeff
    (S : Finset ℕ) (a b c : ℕ) (i : {p : ℕ // p ∈ S}) : ℤ :=
  addCoeff a b c i.1

/-- The coefficient-sum linear form evaluates a unit tangent to the corresponding
raw additive coefficient. -/
theorem additiveLinearFormByCoeff_unitTangent
    (S : Finset ℕ) (a b c : ℕ) (i : {p : ℕ // p ∈ S}) :
    AdditiveLinearFormByCoeff S (unitTangent S i) a b c =
      unitLinearCoeff S a b c i := by
  unfold AdditiveLinearFormByCoeff unitLinearCoeff unitTangent
  rw [Finset.sum_eq_single i]
  · simp
  · intro j _hj hji
    simp [hji]
  · intro hi
    exact False.elim (hi (Finset.mem_univ i))

/-- A unit tangent is nonzero, hence nondegenerate for the current minimal
nondegeneracy predicate. -/
theorem unitTangent_nondegenerate
    (S : Finset ℕ) (i : {p : ℕ // p ∈ S}) :
    Nondegenerate S (unitTangent S i) := by
  unfold Nondegenerate NonzeroTangent
  exact ⟨i, by simp [unitTangent]⟩

/-- A coordinate unit tangent is small with coordinate bound `1`. -/
theorem coordinateAbsBounded_unitTangent_one
    (S : Finset ℕ) (i : {p : ℕ // p ∈ S}) :
    CoordinateAbsBounded S (unitTangent S i) 1 := by
  intro j
  by_cases h : j = i
  · subst j
    simp only [unitTangent_self]
    exact (by decide : |(1 : ℤ)| ≤ 1)
  · rw [unitTangent_of_ne S h]
    exact (by decide : |(0 : ℤ)| ≤ 1)

/-- The same unit-tangent bound in the current `SmallTangent` presentation. -/
theorem smallTangent_unitTangent_one
    (S : Finset ℕ) (i : {p : ℕ // p ∈ S}) :
    SmallTangent S (unitTangent S i) 1 := by
  exact smallTangent_of_coordinateAbsBounded
    (coordinateAbsBounded_unitTangent_one S i)

/-- If the unit coordinate already lies in the kernel, it gives a small
nondegenerate kernel point with bound `1`. -/
theorem unitTangent_mem_additiveKernelSubmodule_of_unitLinearCoeff_zero
    (S : Finset ℕ) (a b c : ℕ) (i : {p : ℕ // p ∈ S})
    (h : unitLinearCoeff S a b c i = 0) :
    unitTangent S i ∈ AdditiveKernelSubmodule S a b c := by
  rw [mem_additiveKernelSubmodule_iff]
  rw [additiveOn_iff_linearForm_zero]
  rw [additiveLinearForm_eq_additiveLinearFormByCoeff]
  rw [additiveLinearFormByCoeff_unitTangent]
  exact h

/-- A packaged small point of a general additive-kernel submodule. -/
structure SmallAdditiveKernelPoint
    (S : Finset ℕ) (a b c : ℕ) (B : ℤ) where
  x : Tangent S
  mem_kernel : x ∈ AdditiveKernelSubmodule S a b c
  nondegenerate : Nondegenerate S x
  small : SmallTangent S x B

/-- Package a unit tangent as a small nondegenerate kernel point when its
additive coefficient is zero. -/
def smallAdditiveKernelPoint_of_unitLinearCoeff_zero
    (S : Finset ℕ) (a b c : ℕ) (i : {p : ℕ // p ∈ S})
    (h : unitLinearCoeff S a b c i = 0) :
    SmallAdditiveKernelPoint S a b c 1 where
  x := unitTangent S i
  mem_kernel :=
    unitTangent_mem_additiveKernelSubmodule_of_unitLinearCoeff_zero
      S a b c i h
  nondegenerate :=
    unitTangent_nondegenerate S i
  small :=
    smallTangent_unitTangent_one S i

/-- The two-coordinate kernel point generated by two support directions.

If `A_i = L(e_i)` and `A_j = L(e_j)`, this is
`A_j e_i - A_i e_j`.  Linearity makes it land in `ker L`.
-/
def twoCoordinateKernelPoint
    (S : Finset ℕ) (a b c : ℕ)
    (i j : {p : ℕ // p ∈ S}) : Tangent S :=
  unitLinearCoeff S a b c j • unitTangent S i -
    unitLinearCoeff S a b c i • unitTangent S j

/-- A coefficient-derived coordinate bound for the two-coordinate kernel point. -/
def twoCoordinateKernelBound
    (S : Finset ℕ) (a b c : ℕ)
    (i j : {p : ℕ // p ∈ S}) : ℤ :=
  |unitLinearCoeff S a b c i| + |unitLinearCoeff S a b c j|

/-- The coefficient linear form is compatible with scalar multiplication. -/
theorem additiveLinearFormByCoeff_smul
    (S : Finset ℕ) (a b c : ℕ) (r : ℤ) (x : Tangent S) :
    AdditiveLinearFormByCoeff S (r • x) a b c =
      r * AdditiveLinearFormByCoeff S x a b c := by
  unfold AdditiveLinearFormByCoeff
  rw [Finset.mul_sum]
  apply Finset.sum_congr rfl
  intro k _hk
  simp [Pi.smul_apply,mul_left_comm, mul_comm]

/-- The two-coordinate construction lies in the coefficient kernel. -/
theorem additiveLinearFormByCoeff_twoCoordinateKernelPoint
    (S : Finset ℕ) (a b c : ℕ)
    (i j : {p : ℕ // p ∈ S}) :
    AdditiveLinearFormByCoeff S
        (twoCoordinateKernelPoint S a b c i j) a b c = 0 := by
  unfold twoCoordinateKernelPoint
  rw [additiveLinearFormByCoeff_sub]
  rw [additiveLinearFormByCoeff_smul]
  rw [additiveLinearFormByCoeff_smul]
  rw [additiveLinearFormByCoeff_unitTangent]
  rw [additiveLinearFormByCoeff_unitTangent]
  simp [mul_comm]

/-- The two-coordinate construction lies in the additive kernel submodule. -/
theorem twoCoordinateKernelPoint_mem_additiveKernelSubmodule
    (S : Finset ℕ) (a b c : ℕ)
    (i j : {p : ℕ // p ∈ S}) :
    twoCoordinateKernelPoint S a b c i j ∈
      AdditiveKernelSubmodule S a b c := by
  rw [mem_additiveKernelSubmodule_iff]
  rw [additiveOn_iff_linearForm_zero]
  rw [additiveLinearForm_eq_additiveLinearFormByCoeff]
  exact additiveLinearFormByCoeff_twoCoordinateKernelPoint S a b c i j

/-- A scalar multiple of a unit tangent is bounded by the absolute value of the scalar. -/
theorem coordinateAbsBounded_smul_unitTangent_abs
    (S : Finset ℕ) (i : {p : ℕ // p ∈ S}) (r : ℤ) :
    CoordinateAbsBounded S (r • unitTangent S i) |r| := by
  intro j
  by_cases h : j = i
  · subst j
    simp [unitTangent, Pi.smul_apply]
  · simp [unitTangent, Pi.smul_apply, h]

/-- Coordinate absolute bounds are stable under subtraction, with additive bound. -/
theorem coordinateAbsBounded_sub
    {S : Finset ℕ} {x y : Tangent S} {Bx By : ℤ}
    (hx : CoordinateAbsBounded S x Bx)
    (hy : CoordinateAbsBounded S y By) :
    CoordinateAbsBounded S (x - y) (Bx + By) := by
  intro k
  have hxk := hx k
  have hyk := hy k
  have htri : |(x - y) k| ≤ |x k| + |y k| := by
    simpa [Pi.sub_apply, sub_eq_add_neg] using
      (abs_add_le (x k) (-(y k)))
  exact le_trans htri (add_le_add hxk hyk)

/-- The coefficient-derived bound really bounds the two-coordinate kernel point. -/
theorem coordinateAbsBounded_twoCoordinateKernelPoint
    (S : Finset ℕ) (a b c : ℕ)
    (i j : {p : ℕ // p ∈ S}) :
    CoordinateAbsBounded S
      (twoCoordinateKernelPoint S a b c i j)
      (twoCoordinateKernelBound S a b c i j) := by
  unfold twoCoordinateKernelPoint twoCoordinateKernelBound
  rw [add_comm]
  exact coordinateAbsBounded_sub
    (coordinateAbsBounded_smul_unitTangent_abs
      S i (unitLinearCoeff S a b c j))
    (coordinateAbsBounded_smul_unitTangent_abs
      S j (unitLinearCoeff S a b c i))

/-- The two-coordinate kernel point is small with its coefficient-derived bound. -/
theorem smallTangent_twoCoordinateKernelPoint
    (S : Finset ℕ) (a b c : ℕ)
    (i j : {p : ℕ // p ∈ S}) :
    SmallTangent S
      (twoCoordinateKernelPoint S a b c i j)
      (twoCoordinateKernelBound S a b c i j) := by
  exact smallTangent_of_coordinateAbsBounded
    (coordinateAbsBounded_twoCoordinateKernelPoint S a b c i j)

/-- If the left coefficient is nonzero, the two-coordinate point is nondegenerate. -/
theorem twoCoordinateKernelPoint_nondegenerate_of_leftCoeff_ne_zero
    (S : Finset ℕ) (a b c : ℕ)
    {i j : {p : ℕ // p ∈ S}}
    (hij : i ≠ j)
    (hi : unitLinearCoeff S a b c i ≠ 0) :
    Nondegenerate S (twoCoordinateKernelPoint S a b c i j) := by
  unfold Nondegenerate NonzeroTangent
  refine ⟨j, ?_⟩
  have hji : j ≠ i := Ne.symm hij
  unfold twoCoordinateKernelPoint
  simp only [Pi.sub_apply]
  simpa [unitTangent, hji] using hi

/-- If the right coefficient is nonzero, the two-coordinate point is nondegenerate. -/
theorem twoCoordinateKernelPoint_nondegenerate_of_rightCoeff_ne_zero
    (S : Finset ℕ) (a b c : ℕ)
    {i j : {p : ℕ // p ∈ S}}
    (hij : i ≠ j)
    (hj : unitLinearCoeff S a b c j ≠ 0) :
    Nondegenerate S (twoCoordinateKernelPoint S a b c i j) := by
  unfold Nondegenerate NonzeroTangent
  refine ⟨i, ?_⟩
  unfold twoCoordinateKernelPoint
  simp only [Pi.sub_apply]
  simpa [unitTangent, hij] using hj

/-- If at least one of the two coefficients is nonzero, the two-coordinate point
is nondegenerate. -/
theorem twoCoordinateKernelPoint_nondegenerate_of_coeff_ne_zero
    (S : Finset ℕ) (a b c : ℕ)
    {i j : {p : ℕ // p ∈ S}}
    (hij : i ≠ j)
    (hcoeff :
      unitLinearCoeff S a b c i ≠ 0 ∨
      unitLinearCoeff S a b c j ≠ 0) :
    Nondegenerate S (twoCoordinateKernelPoint S a b c i j) := by
  cases hcoeff with
  | inl hi =>
      exact twoCoordinateKernelPoint_nondegenerate_of_leftCoeff_ne_zero
        S a b c hij hi
  | inr hj =>
      exact twoCoordinateKernelPoint_nondegenerate_of_rightCoeff_ne_zero
        S a b c hij hj

/-- Package the two-coordinate kernel point as a small nondegenerate kernel point. -/
def smallAdditiveKernelPoint_twoCoordinateKernelPoint
    (S : Finset ℕ) (a b c : ℕ)
    (i j : {p : ℕ // p ∈ S})
    (hij : i ≠ j)
    (hcoeff :
      unitLinearCoeff S a b c i ≠ 0 ∨
      unitLinearCoeff S a b c j ≠ 0) :
    SmallAdditiveKernelPoint S a b c
      (twoCoordinateKernelBound S a b c i j) where
  x := twoCoordinateKernelPoint S a b c i j
  mem_kernel :=
    twoCoordinateKernelPoint_mem_additiveKernelSubmodule S a b c i j
  nondegenerate :=
    twoCoordinateKernelPoint_nondegenerate_of_coeff_ne_zero
      S a b c hij hcoeff
  small :=
    smallTangent_twoCoordinateKernelPoint S a b c i j

/-- A support pair always gives some explicit small nondegenerate additive-kernel point.

If the left coefficient is zero, use the left unit tangent.
Otherwise, use the two-coordinate construction.
-/
def smallAdditiveKernelPoint_of_supportPair
    (S : Finset ℕ) (a b c : ℕ) (pair : SupportPair S) :
    Σ B : ℤ, SmallAdditiveKernelPoint S a b c B := by
  by_cases hleft : unitLinearCoeff S a b c pair.left = 0
  · exact
      ⟨1,
        smallAdditiveKernelPoint_of_unitLinearCoeff_zero
          S a b c pair.left hleft⟩
  · exact
      ⟨twoCoordinateKernelBound S a b c pair.left pair.right,
        smallAdditiveKernelPoint_twoCoordinateKernelPoint
          S a b c pair.left pair.right pair.ne (Or.inl hleft)⟩

/-- Existence form of the pre-Siegel small kernel-point construction. -/
theorem exists_smallAdditiveKernelPoint_of_supportPair
    (S : Finset ℕ) (a b c : ℕ) (P : SupportPair S) :
    ∃ B : ℤ, Nonempty (SmallAdditiveKernelPoint S a b c B) := by
  let h := smallAdditiveKernelPoint_of_supportPair S a b c P
  exact ⟨h.1, ⟨h.2⟩⟩

/-- Triple-specialized name for the same small kernel-point package. -/
abbrev SmallTripleKernelPoint (T : ABCTriple) (B : ℤ) : Type :=
  SmallAdditiveKernelPoint T.support T.a T.b T.c B

/-- A pair of support directions for an additive triple. -/
abbrev TripleSupportPair (T : ABCTriple) : Type :=
  SupportPair T.support

/-- The pre-Siegel construction specialized to an additive triple. -/
def smallTripleKernelPoint_of_supportPair
    (T : ABCTriple) (P : TripleSupportPair T) :
    Σ B : ℤ, SmallTripleKernelPoint T B :=
  smallAdditiveKernelPoint_of_supportPair T.support T.a T.b T.c P

/-- A triple small kernel point also lies in the existing triple additive-kernel
submodule. -/
theorem SmallTripleKernelPoint.mem_tripleAdditiveKernelSubmodule
    {T : ABCTriple} {B : ℤ} (h : SmallTripleKernelPoint T B) :
    h.x ∈ TripleAdditiveKernelSubmodule T := by
  rw [mem_tripleAdditiveKernelSubmodule_iff]
  exact (mem_additiveKernelSubmodule_iff T.support h.x T.a T.b T.c).1
    h.mem_kernel

end ABD
