import ABD.BQD.Bit.Active
import ABD.BQD.Bit.Additive.Eval

namespace ABD
namespace BQD
namespace Bit
namespace Additive

/-- The additive four-atom board for a common-width pair of bit sets.

This is the pre-normal-form layer.  It stores the idempotent parts
`B/LO/RO/N` of a two-input bit board, but it does not yet store a target
integer `c`.  The candidate sum is derived later as
`xorValue + 2 * andValue`. -/
structure Board (width : ℕ) where
  /-- Both-active positions: the `a & b` atom. -/
  B : Finset ℕ
  /-- Left-only positions: the `a & ¬b` atom. -/
  LO : Finset ℕ
  /-- Right-only positions: the `¬a & b` atom. -/
  RO : Finset ℕ
  /-- Neither-active positions: the `¬a & ¬b` atom. -/
  N : Finset ℕ
  hB : B ⊆ bitUniverse width
  hLO : LO ⊆ bitUniverse width
  hRO : RO ⊆ bitUniverse width
  hN : N ⊆ bitUniverse width
  hB_LO : B ∩ LO = (∅ : Finset ℕ)
  hB_RO : B ∩ RO = (∅ : Finset ℕ)
  hB_N : B ∩ N = (∅ : Finset ℕ)
  hLO_RO : LO ∩ RO = (∅ : Finset ℕ)
  hLO_N : LO ∩ N = (∅ : Finset ℕ)
  hRO_N : RO ∩ N = (∅ : Finset ℕ)
  hcover : B ∪ LO ∪ RO ∪ N = bitUniverse width

namespace Board

variable {width : ℕ}

/-- Integer value of the both-active atom. -/
def valB (G : Board width) : ℕ :=
  evalMask G.B

/-- Integer value of the left-only atom. -/
def valLO (G : Board width) : ℕ :=
  evalMask G.LO

/-- Integer value of the right-only atom. -/
def valRO (G : Board width) : ℕ :=
  evalMask G.RO

/-- Integer value of the neither-active atom. -/
def valN (G : Board width) : ℕ :=
  evalMask G.N

/-- Left integer generated by the board: `a = B + LO`. -/
def a (G : Board width) : ℕ :=
  G.valB + G.valLO

/-- Right integer generated by the board: `b = B + RO`. -/
def b (G : Board width) : ℕ :=
  G.valB + G.valRO

/-- Integer value of the `a & b` mask. -/
def andValue (G : Board width) : ℕ :=
  G.valB

/-- Integer value of the `a xor b` mask. -/
def xorValue (G : Board width) : ℕ :=
  G.valLO + G.valRO

/-- Integer value of the `a | b` mask. -/
def orValue (G : Board width) : ℕ :=
  G.valB + G.valLO + G.valRO

/-- Candidate additive output generated from the board.

This is the pre-normal-form expression `(a xor b) + 2 * (a & b)`.
The true `NormalForm` later supplies an actual `c` and the equality
`candidateC = c`. -/
def candidateC (G : Board width) : ℕ :=
  G.xorValue + 2 * G.andValue

@[simp] theorem valB_def (G : Board width) :
    G.valB = evalMask G.B := rfl

@[simp] theorem valLO_def (G : Board width) :
    G.valLO = evalMask G.LO := rfl

@[simp] theorem valRO_def (G : Board width) :
    G.valRO = evalMask G.RO := rfl

@[simp] theorem valN_def (G : Board width) :
    G.valN = evalMask G.N := rfl

@[simp] theorem a_def (G : Board width) :
    G.a = G.valB + G.valLO := rfl

@[simp] theorem b_def (G : Board width) :
    G.b = G.valB + G.valRO := rfl

@[simp] theorem andValue_def (G : Board width) :
    G.andValue = G.valB := rfl

@[simp] theorem xorValue_def (G : Board width) :
    G.xorValue = G.valLO + G.valRO := rfl

@[simp] theorem orValue_def (G : Board width) :
    G.orValue = G.valB + G.valLO + G.valRO := rfl

@[simp] theorem candidateC_def (G : Board width) :
    G.candidateC = G.xorValue + 2 * G.andValue := rfl

/-- The board candidate is exactly the sum of its generated inputs. -/
@[simp] theorem add_eq_candidateC (G : Board width) :
    G.a + G.b = G.candidateC := by
  dsimp [a, b, candidateC, xorValue, andValue, valB, valLO, valRO]
  rw [two_mul]
  ac_rfl

/-- Expanded form of the candidate output. -/
theorem candidateC_eq_valLO_add_valRO_add_two_mul_valB (G : Board width) :
    G.candidateC = G.valLO + G.valRO + 2 * G.valB := rfl

end Board
end Additive
end Bit
end BQD
end ABD
