import ABD.BQD.Bit.Active
import ABD.BQD.Bit.Additive.Eval

namespace ABD
namespace BQD
namespace Bit
namespace Additive

/-- Additive bit normal form, in the Finset-based version.

The four masks `B`, `LO`, `RO`, and `N` are the four idempotent atoms of a
common-width two-input bit board:

* `B`: both-active positions,
* `LO`: left-only positions,
* `RO`: right-only positions,
* `N`: neither-active positions.

They are stored as finite sets of bit positions.  Integer values are obtained
only through `evalMask`; this keeps the Boolean/idempotent layer separate from
ordinary integer addition. -/
structure NormalForm (width : ℕ) where
  B : Finset ℕ
  LO : Finset ℕ
  RO : Finset ℕ
  N : Finset ℕ
  hB : B ⊆ bitUniverse width
  hLO : LO ⊆ bitUniverse width
  hRO : RO ⊆ bitUniverse width
  hN : N ⊆ bitUniverse width
  hB_LO : B ∩ LO = (∅ : Finset ℕ)
  hB_RO : B ∩ RO = (∅ : Finset ℕ)
  hB_N : B ∩ N = (∅ : Finset ℕ)
  hLO_RO : LO ∩ RO = (∅ : Finset ℕ)
  hLO_N : LO ∩ N = (∅ : Finset ℕ)
  hRO_N : RO ∩ N = (∅ : Finset ℕ)
  hcover : B ∪ LO ∪ RO ∪ N = bitUniverse width

namespace NormalForm

variable {width : ℕ}

/-- Integer value of the both-active atom. -/
def valB (F : NormalForm width) : ℕ :=
  evalMask F.B

/-- Integer value of the left-only atom. -/
def valLO (F : NormalForm width) : ℕ :=
  evalMask F.LO

/-- Integer value of the right-only atom. -/
def valRO (F : NormalForm width) : ℕ :=
  evalMask F.RO

/-- Integer value of the neither-active atom. -/
def valN (F : NormalForm width) : ℕ :=
  evalMask F.N

/-- Left integer generated by the normal form: `a = B + LO`. -/
def a (F : NormalForm width) : ℕ :=
  F.valB + F.valLO

/-- Right integer generated by the normal form: `b = B + RO`. -/
def b (F : NormalForm width) : ℕ :=
  F.valB + F.valRO

/-- Carry-free xor value: `LO + RO`. -/
def xorValue (F : NormalForm width) : ℕ :=
  F.valLO + F.valRO

/-- Bitwise-or value before carry duplication: `B + LO + RO`. -/
def orValue (F : NormalForm width) : ℕ :=
  F.valB + F.valLO + F.valRO

/-- Integer generated by the normal form: `c = LO + RO + 2B`. -/
def c (F : NormalForm width) : ℕ :=
  F.valLO + F.valRO + 2 * F.valB

@[simp] theorem a_def (F : NormalForm width) :
    F.a = F.valB + F.valLO := rfl

@[simp] theorem b_def (F : NormalForm width) :
    F.b = F.valB + F.valRO := rfl

@[simp] theorem xorValue_def (F : NormalForm width) :
    F.xorValue = F.valLO + F.valRO := rfl

@[simp] theorem orValue_def (F : NormalForm width) :
    F.orValue = F.valB + F.valLO + F.valRO := rfl

@[simp] theorem c_def (F : NormalForm width) :
    F.c = F.valLO + F.valRO + 2 * F.valB := rfl

/-- Soundness of the additive normal form.

Every Finset-based idempotent board generates a triple satisfying `a + b = c`
when read by integer evaluation and the rule
`a = B + LO`, `b = B + RO`, `c = LO + RO + 2B`. -/
@[simp] theorem add_eq_c (F : NormalForm width) :
    F.a + F.b = F.c := by
  dsimp [a, b, c, valB, valLO, valRO]
  rw [two_mul]
  ac_rfl

/-- The generated `c` is xor value plus twice the both-active value. -/
@[simp] theorem c_eq_xorValue_add_two_mul_valB (F : NormalForm width) :
    F.c = F.xorValue + 2 * F.valB := rfl

/-- The difference between `c` and the xor value is carried by the both-active atom. -/
theorem c_eq_valLO_add_valRO_add_two_mul_valB (F : NormalForm width) :
    F.c = F.valLO + F.valRO + 2 * F.valB := rfl

end NormalForm
end Additive
end Bit
end BQD
end ABD
