/-
  ABD.ApparitionDepth3.BranchGenerator

  Concrete branch seeds from a primitive generator modulo p.
-/

import ABD.ApparitionDepth3.Hensel

namespace ApparitionDepth3

/-- A natural representative whose unit modulo `p` has the full order `p - 1`. -/
def PrimitiveRootModP (g p : Nat) (hcop : g.Coprime p) : Prop :=
  OrderModIs g p (p - 1) hcop

/-- The exponent selecting the `(d,j)` branch from a primitive generator. -/
def branchExponent (p d j : Nat) : Nat :=
  ((p - 1) / d) * j

/-- The natural seed of the `(d,j)` branch generated by `g`. -/
def branchSeed (g p d j : Nat) : Nat :=
  g ^ branchExponent p d j

/-- A branch seed is coprime to `p` whenever the primitive generator is. -/
theorem branchSeed_coprime
    {g p d j : Nat}
    (hcopG : g.Coprime p) :
    (branchSeed g p d j).Coprime p := by
  unfold branchSeed
  exact hcopG.pow_left _

/-- The unit represented by the concrete branch seed is the corresponding
power of the primitive generator unit. -/
theorem unitMod_branchSeed
    {g p d j : Nat}
    (hcopG : g.Coprime p) :
    unitMod (branchSeed g p d j) p (branchSeed_coprime hcopG) =
      (unitMod g p hcopG) ^ branchExponent p d j := by
  apply Units.ext
  simp [branchSeed, coe_unitMod, Nat.cast_pow]

/-- A proper divisor of `p - 1` is strictly below the prime `p`. -/
theorem branchParams_d_lt_prime
    {p d j : Nat} [Fact p.Prime]
    (hparams : BranchParams p d j) :
    d < p := by
  have hp : p.Prime := Fact.out
  have hpSubPos : 0 < p - 1 := Nat.sub_pos_of_lt hp.one_lt
  have hdLe : d ≤ p - 1 := Nat.le_of_dvd hpSubPos hparams.1
  omega

/-- The branch order `d` is coprime to the target prime `p`. -/
theorem branchParams_d_coprime_prime
    {p d j : Nat} [Fact p.Prime]
    (hparams : BranchParams p d j) :
    d.Coprime p := by
  have hp : p.Prime := Fact.out
  have hdPos : 0 < d := branchParams_d_pos hparams
  have hdLt : d < p := branchParams_d_lt_prime hparams
  have hnot : ¬ p ∣ d := by
    intro hpd
    have hpLe : p ≤ d := Nat.le_of_dvd hdPos hpd
    exact (not_lt_of_ge hpLe) hdLt
  exact (hp.coprime_iff_not_dvd.mpr hnot).symm

/-- The concrete `(d,j)` branch seed has exact multiplicative order `d`. -/
theorem branchSeed_orderModIs
    {g p d j : Nat} [Fact p.Prime]
    (hcopG : g.Coprime p)
    (hprimitive : PrimitiveRootModP g p hcopG)
    (hparams : BranchParams p d j) :
    OrderModIs (branchSeed g p d j) p d (branchSeed_coprime hcopG) := by
  let x : (ZMod p)ˣ := unitMod g p hcopG
  have horderX : orderOf x = p - 1 := by
    exact hprimitive
  have horderXNe : orderOf x ≠ 0 := by
    rw [horderX]
    exact (Nat.sub_pos_of_lt (Fact.out : Nat.Prime p).one_lt).ne'
  have hdvdOrder : d ∣ orderOf x := by
    rw [horderX]
    exact branchParams_dvd hparams
  have hbaseOrder : orderOf (x ^ (orderOf x / d)) = d :=
    orderOf_pow_orderOf_div (x := x) (n := d) horderXNe hdvdOrder
  have hbaseOrder' : orderOf (x ^ ((p - 1) / d)) = d := by
    simpa [horderX] using hbaseOrder
  have hcopOrderJ : (orderOf (x ^ ((p - 1) / d))).Coprime j := by
    rw [hbaseOrder']
    exact (branchParams_index hparams).2.2.symm
  have hbranchOrder : orderOf ((x ^ ((p - 1) / d)) ^ j) = d := by
    rw [hcopOrderJ.orderOf_pow, hbaseOrder']
  unfold OrderModIs orderMod
  rw [unitMod_branchSeed hcopG]
  simpa [branchExponent, pow_mul] using hbranchOrder

/-- Exact order supplies the root equation at level one. -/
theorem branchSeed_rootAtLevel_one
    {g p d j : Nat} [Fact p.Prime]
    (hcopG : g.Coprime p)
    (hprimitive : PrimitiveRootModP g p hcopG)
    (hparams : BranchParams p d j) :
    RootAtLevel (branchSeed g p d j) p d 1 := by
  let hcopSeed := branchSeed_coprime (g := g) (d := d) (j := j) hcopG
  have hord : OrderModIs (branchSeed g p d j) p d hcopSeed :=
    branchSeed_orderModIs hcopG hprimitive hparams
  have hpow : UnitPowOneAt (branchSeed g p d j) p d hcopSeed :=
    orderModIs_unitPowOneAt hord
  have hres : ((branchSeed g p d j : Nat) : ZMod p) ^ d = 1 :=
    (unitPowOneAt_iff_residuePowOne hcopSeed).mp hpow
  unfold RootAtLevel
  rw [levelOneModulus_eq p]
  exact hres

/-- The derivative at a concrete branch seed is a unit modulo `p`. -/
theorem branchSeed_derivative_unit
    {g p d j : Nat} [Fact p.Prime]
    (hcopG : g.Coprime p)
    (hparams : BranchParams p d j) :
    IsUnit (derivativeAt (branchSeed g p d j) p d) := by
  have hcopSeed : (branchSeed g p d j).Coprime p := branchSeed_coprime hcopG
  have hseedUnit : IsUnit ((branchSeed g p d j : Nat) : ZMod p) :=
    (ZMod.isUnit_iff_coprime (branchSeed g p d j) p).mpr hcopSeed
  have hdUnit : IsUnit ((d : Nat) : ZMod p) :=
    (ZMod.isUnit_iff_coprime d p).mpr (branchParams_d_coprime_prime hparams)
  unfold derivativeAt
  exact hdUnit.mul (hseedUnit.pow (d - 1))

/-- Every primitive-generator branch seed is a simple root of `X^d - 1` modulo
`p`. -/
theorem branchSeed_simpleRoot
    {g p d j : Nat} [Fact p.Prime]
    (hcopG : g.Coprime p)
    (hprimitive : PrimitiveRootModP g p hcopG)
    (hparams : BranchParams p d j) :
    SimpleRootModP (branchSeed g p d j) p d :=
  simpleRoot_intro
    (branchSeed_rootAtLevel_one hcopG hprimitive hparams)
    (branchSeed_derivative_unit hcopG hparams)

end ApparitionDepth3
