import ABD.BQD.Bit.Additive2.Eval

namespace ABD
namespace BQD
namespace Bit
namespace Additive2

/-- Width-free additive three-atom board.

This is the pre-normal-form layer.  It stores only the three atoms that
actually generate addition:

* `B`  : both-active positions, the `a & b` atom;
* `LO` : left-only positions, the `a & ~b` atom;
* `RO` : right-only positions, the `~a & b` atom.

The neither-active atom `N` is deliberately absent here.  It is not needed to
construct `a`, `b`, or `(a xor b) + 2 * (a & b)`.  In `NormalForm c`, `N` is
recovered as the complement of `B ∪ LO ∪ RO` inside the canonical universe
`bitUniverse (bitLength c)`. -/
structure Board where
  /-- Both-active positions: the `a & b` atom. -/
  B : Finset ℕ
  /-- Left-only positions: the `a & ¬b` atom. -/
  LO : Finset ℕ
  /-- Right-only positions: the `¬a & b` atom. -/
  RO : Finset ℕ
  /-- Orthogonality of `B` and `LO`. -/
  hB_LO : B ∩ LO = (∅ : Finset ℕ)
  /-- Orthogonality of `B` and `RO`. -/
  hB_RO : B ∩ RO = (∅ : Finset ℕ)
  /-- Orthogonality of `LO` and `RO`. -/
  hLO_RO : LO ∩ RO = (∅ : Finset ℕ)

namespace Board

/-- The active part generated by the three additive atoms. -/
def active (G : Board) : Finset ℕ :=
  G.B ∪ G.LO ∪ G.RO

/-- Integer value of the both-active atom. -/
def valB (G : Board) : ℕ :=
  evalMask G.B

/-- Integer value of the left-only atom. -/
def valLO (G : Board) : ℕ :=
  evalMask G.LO

/-- Integer value of the right-only atom. -/
def valRO (G : Board) : ℕ :=
  evalMask G.RO

/-- Left integer generated by the board: `a = B + LO`. -/
def a (G : Board) : ℕ :=
  G.valB + G.valLO

/-- Right integer generated by the board: `b = B + RO`. -/
def b (G : Board) : ℕ :=
  G.valB + G.valRO

/-- Integer value of the `a & b` mask. -/
def andValue (G : Board) : ℕ :=
  G.valB

/-- Integer value of the `a xor b` mask. -/
def xorValue (G : Board) : ℕ :=
  G.valLO + G.valRO

/-- Integer value of the `a | b` mask. -/
def orValue (G : Board) : ℕ :=
  G.valB + G.valLO + G.valRO

/-- Candidate additive output generated from the board.

This is the pre-normal-form expression `(a xor b) + 2 * (a & b)`.
The true `NormalForm c` later supplies an actual output `c` and the equality
`candidateC = c`. -/
def candidateC (G : Board) : ℕ :=
  G.xorValue + 2 * G.andValue

@[simp] theorem active_def (G : Board) :
    G.active = G.B ∪ G.LO ∪ G.RO := rfl

@[simp] theorem valB_def (G : Board) :
    G.valB = evalMask G.B := rfl

@[simp] theorem valLO_def (G : Board) :
    G.valLO = evalMask G.LO := rfl

@[simp] theorem valRO_def (G : Board) :
    G.valRO = evalMask G.RO := rfl

@[simp] theorem a_def (G : Board) :
    G.a = G.valB + G.valLO := rfl

@[simp] theorem b_def (G : Board) :
    G.b = G.valB + G.valRO := rfl

@[simp] theorem andValue_def (G : Board) :
    G.andValue = G.valB := rfl

@[simp] theorem xorValue_def (G : Board) :
    G.xorValue = G.valLO + G.valRO := rfl

@[simp] theorem orValue_def (G : Board) :
    G.orValue = G.valB + G.valLO + G.valRO := rfl

@[simp] theorem candidateC_def (G : Board) :
    G.candidateC = G.xorValue + 2 * G.andValue := rfl

/-- The board candidate is exactly the sum of its generated inputs.

This is the key width-free additive identity. -/
@[simp] theorem add_eq_candidateC (G : Board) :
    G.a + G.b = G.candidateC := by
  dsimp [a, b, candidateC, xorValue, andValue, valB, valLO, valRO]
  rw [Nat.two_mul]
  ac_rfl

/-- Expanded form of the candidate output. -/
theorem candidateC_eq_valLO_add_valRO_add_two_mul_valB (G : Board) :
    G.candidateC = G.valLO + G.valRO + 2 * G.valB := rfl

end Board
end Additive2
end Bit
end BQD
end ABD
