import Mathlib.Data.Nat.BitIndices
import ABD.BQD.Bit.Additive2.FromDecomp
import ABD.BQD.Bit.Additive2.EvalLaws

namespace ABD
namespace BQD
namespace Bit
namespace Additive2

/-- Width-truncated integer value of the active bits of `n`.

This is the concrete bridge between the finite-set bit board and the ordinary
natural-number value.  It reads the active positions of `n` inside
`0, ..., width-1` back as the integer `Σ 2^i`. -/
def maskedValue (width n : ℕ) : ℕ :=
  evalMask (bitActive width n)

@[simp] theorem maskedValue_def (width n : ℕ) :
    maskedValue width n = evalMask (bitActive width n) := rfl

/-- If `n` fits in the common width, then its active bit positions are exactly
`Nat.bitIndices n` as a finset.

This isolates the only genuinely bit-expansion part of the additive entrance
argument. -/
theorem bitActive_eq_bitIndices_toFinset_of_lt {width n : ℕ}
    (h : n < 2 ^ width) :
    bitActive width n = n.bitIndices.toFinset := by
  ext i
  constructor
  · intro hi
    have htest : n.testBit i := (mem_bitActive.mp hi).2
    simpa [Nat.mem_bitIndices] using htest
  · intro hi
    have htest : n.testBit i := by
      simpa [Nat.mem_bitIndices] using hi
    have hiw : i < width := by
      by_contra hnot
      have hwi : width ≤ i := le_of_not_gt hnot
      have hpow : 2 ^ width ≤ 2 ^ i :=
        Nat.pow_le_pow_right (by omega : 1 ≤ 2) hwi
      have hnlt : n < 2 ^ i := lt_of_lt_of_le h hpow
      have hfalse : n.testBit i = false := Nat.testBit_eq_false_of_lt hnlt
      have : False := by
        simp [hfalse] at htest
      exact False.elim this
    exact mem_bitActive.mpr ⟨hiw, htest⟩

/-- Completeness of `evalMask` on bounded natural numbers.

If `n < 2^width`, then extracting the active bit positions of `n` inside the
common width and evaluating them as a mask recovers `n` exactly. -/
theorem maskedValue_eq_self_of_lt {width n : ℕ}
    (h : n < 2 ^ width) :
    maskedValue width n = n := by
  rw [maskedValue, bitActive_eq_bitIndices_toFinset_of_lt h]
  simp [evalMask, List.sum_toFinset _ Nat.bitIndices_sorted.nodup]

/-- The left value generated by the pair board is the width-truncated value of
`x`. -/
theorem boardOfPair_a_eq_maskedValue (width x y : ℕ) :
    (boardOfPair width x y).a = maskedValue width x := by
  unfold maskedValue
  calc
    (boardOfPair width x y).a
        = evalMask (decomp width x y).B + evalMask (decomp width x y).LO := by
            rfl
    _ = evalMask ((decomp width x y).B ∪ (decomp width x y).LO) := by
            symm
            exact evalMask_union_of_disjoint
              (disjoint_of_inter_eq_empty ((decomp width x y).B_inter_LO_eq_empty))
    _ = evalMask (bitActive width x) := by
            rw [(decomp width x y).B_union_LO_eq_L]
            rfl

/-- The right value generated by the pair board is the width-truncated value of
`y`. -/
theorem boardOfPair_b_eq_maskedValue (width x y : ℕ) :
    (boardOfPair width x y).b = maskedValue width y := by
  unfold maskedValue
  calc
    (boardOfPair width x y).b
        = evalMask (decomp width x y).B + evalMask (decomp width x y).RO := by
            rfl
    _ = evalMask ((decomp width x y).B ∪ (decomp width x y).RO) := by
            symm
            exact evalMask_union_of_disjoint
              (disjoint_of_inter_eq_empty ((decomp width x y).B_inter_RO_eq_empty))
    _ = evalMask (bitActive width y) := by
            rw [(decomp width x y).B_union_RO_eq_R]
            rfl

/-- Under `x + y = c` and `c < 2^width`, the pair board's left value is the
actual input `x`. -/
theorem boardOfPair_a_eq_left_of_add_eq_of_c_lt {width x y c : ℕ}
    (hadd : x + y = c) (hc : c < 2 ^ width) :
    (boardOfPair width x y).a = x := by
  have hx : x < 2 ^ width := by omega
  rw [boardOfPair_a_eq_maskedValue]
  exact maskedValue_eq_self_of_lt hx

/-- Under `x + y = c` and `c < 2^width`, the pair board's right value is the
actual input `y`. -/
theorem boardOfPair_b_eq_right_of_add_eq_of_c_lt {width x y c : ℕ}
    (hadd : x + y = c) (hc : c < 2 ^ width) :
    (boardOfPair width x y).b = y := by
  have hy : y < 2 ^ width := by omega
  rw [boardOfPair_b_eq_maskedValue]
  exact maskedValue_eq_self_of_lt hy

/-- Under `x + y = c` and `c < 2^width`, the board candidate is exactly the
actual output `c`.

This is the heavy bridge needed by the entrance/completeness layer. -/
theorem boardOfPair_candidateC_eq_of_add_eq_of_c_lt {width x y c : ℕ}
    (hadd : x + y = c) (hc : c < 2 ^ width) :
    (boardOfPair width x y).candidateC = c := by
  calc
    (boardOfPair width x y).candidateC
        = (boardOfPair width x y).a + (boardOfPair width x y).b := by
            exact (Board.add_eq_candidateC (boardOfPair width x y)).symm
    _ = x + y := by
            rw [boardOfPair_a_eq_left_of_add_eq_of_c_lt hadd hc,
              boardOfPair_b_eq_right_of_add_eq_of_c_lt hadd hc]
    _ = c := hadd

/-- Canonical-width specialization: under `x + y = c`, the pair board built at
`bitLength c` has left value `x`. -/
theorem boardOfPair_a_eq_left_of_add_eq {x y c : ℕ}
    (hadd : x + y = c) :
    (boardOfPair (bitLength c) x y).a = x := by
  exact boardOfPair_a_eq_left_of_add_eq_of_c_lt hadd (lt_two_pow_bitLength c)

/-- Canonical-width specialization: under `x + y = c`, the pair board built at
`bitLength c` has right value `y`. -/
theorem boardOfPair_b_eq_right_of_add_eq {x y c : ℕ}
    (hadd : x + y = c) :
    (boardOfPair (bitLength c) x y).b = y := by
  exact boardOfPair_b_eq_right_of_add_eq_of_c_lt hadd (lt_two_pow_bitLength c)

/-- Canonical-width specialization: under `x + y = c`, the pair board built at
`bitLength c` has candidate output `c`. -/
theorem boardOfPair_candidateC_eq_of_add_eq {x y c : ℕ}
    (hadd : x + y = c) :
    (boardOfPair (bitLength c) x y).candidateC = c := by
  exact boardOfPair_candidateC_eq_of_add_eq_of_c_lt hadd (lt_two_pow_bitLength c)

end Additive2
end Bit
end BQD
end ABD
