/-
  ABD.ApparitionDepth2.Branch

  Public branch seed layer.

  Public theorem theme:
    primitive-root branch data produces a seed root modulo `p`.
-/

import ABD.ApparitionDepth.BranchSeedRootProof
import ABD.ApparitionDepth2.ZModBridge

namespace ApparitionDepth2

/-- Branch index package `1 <= j <= d`, `gcd j d = 1`, plus `d | p-1`. -/
abbrev BranchParams (p d j : Nat) : Prop :=
  ApparitionDepth.BranchParams p d j

/-- Archived primitive-root predicate. -/
abbrev PrimitiveRootModP (g p : Nat) : Prop :=
  ApparitionDepth.PrimitiveRootModP g p

/-- Seed congruence modulo `p`. -/
abbrev BranchSeedModP (g omega p d j : Nat) : Prop :=
  ApparitionDepth.BranchSeedModP g omega p d j

/-- The seed value generated by `g, p, d, j`. -/
abbrev branchSeedValue (g p d j : Nat) : ZMod p :=
  ApparitionDepth.branchSeedValue g p d j

/-- The branch seed is a root modulo `p`. -/
abbrev BranchSeedRootModP (g p d j : Nat) : Prop :=
  ApparitionDepth.BranchSeedRootModP g p d j

/-- A concrete finite branch representative. -/
abbrev OmegaBranchAtLevel (g omega p d j r : Nat) : Prop :=
  ApparitionDepth.OmegaBranchAtLevel g omega p d j r

/-- A base lies in a generated omega branch at level `r`. -/
abbrev BaseInOmegaBranch (ell omega p d j r : Nat) : Prop :=
  ApparitionDepth.BaseInOmegaBranch ell omega p d j r

/-- Primitive-root branch data proves that the seed is a `d`-th root modulo `p`. -/
theorem branchSeed_root_mod_p_of_primitiveRoot
    {g p d j : Nat}
    (hprim : PrimitiveRootModP g p)
    (hparams : BranchParams p d j) :
    BranchSeedRootModP g p d j :=
  ApparitionDepth.branchSeedRootModP_of_primitiveRoot hprim hparams

/-- A seed representative gives a root at level `1`. -/
theorem rootAtLevel_one_of_branchSeed_of_primitiveRoot
    {g omega p d j : Nat}
    (hprim : PrimitiveRootModP g p)
    (hparams : BranchParams p d j)
    (hseed : BranchSeedModP g omega p d j) :
    RootAtLevel omega p d 1 :=
  ApparitionDepth.omegaRootAtLevel_one_of_branchSeed_of_primitiveRoot
    hprim hparams hseed

/-- A base in an omega branch is a root at the same level.

This is the first RootAtLevel-centered public exit: branch membership is kept in
the residue-ring language before being translated back to Core depth. -/
theorem rootAtLevel_of_baseInOmegaBranch
    {ell omega p d j r : Nat}
    (hbranch : BaseInOmegaBranch ell omega p d j r) :
    RootAtLevel ell p d r :=
  ApparitionDepth.movingBaseClass_residueDepthAtLeast
    (ApparitionDepth.movingBaseClass_of_baseInOmegaBranch hbranch)

/-- A positive base in an omega branch has depth at least `r`. -/
theorem depthAtLeast_of_baseInOmegaBranch_of_base_pos
    {ell omega p d j r : Nat}
    (hbranch : BaseInOmegaBranch ell omega p d j r)
    (hell_pos : 0 < ell) :
    DepthAtLeast ell p d r :=
  depthAtLeast_of_rootAtLevel_of_base_pos hell_pos
    (rootAtLevel_of_baseInOmegaBranch hbranch)

end ApparitionDepth2
